### ISSUE TITLE
As an Agency I want to enable two-factor/Multifactor authentication for my user accounts

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#1]
_From @pandaskii on October 18, 2017 4:34_

Modules on the radar:

- Two-factor Authentication (TFA) https://www.drupal.org/project/tfa

_Copied from original issue: govCMS/govCMS8-core#12_

**Comment by tobybellwood** [comment]
_From @pandaskii on October 18, 2017 4:36_

TFA module is a little bit buggy at the current stage. 

https://www.drupal.org/forum/support/post-installation/2016-10-18/how-do-i-enable-tfa-in-drupal-8

https://www.drupal.org/project/issues/tfa?text=&status=Open&priorities=All&categories=All&version=8.x&component=All

**Comment by tobybellwood** [comment]
From current discussion on Drupal Slack, it seems like support for https://www.drupal.org/project/ga_login is preferred over tfa_basic https://www.drupal.org/node/2922276

**Comment by simesy** [comment]
Closing this as stale. Please reopen with an update if appropriate, and if this is linked to a Jira ticket please provide reference.
