### ISSUE TITLE
Moar Behat tests

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#100]
Referencing some of the tests present in GovCMS 7 (https://github.com/govCMS/govCMS/tree/7.x-2.x/build/tests/behat), we should start to expand on the Behat tests currently in place for GovCMS8

**Comment by tobybellwood** [comment]
(note that some work is currently being undertaken by @pandaskii  on making those tests more PHP7 friendly

**Comment by simesy** [comment]
Marking as dupe of https://github.com/govCMS/govCMS8/issues/14
