### ISSUE TITLE
Simple XML Sitemap module not enabled after installation

### ISSUE THREAD

**Issue by petrillek** [govCMS/govcms8-installer#106]
As a developer I need to be able to export/import config after installation without errors.

###  Issue description
Four of five optional modules for content types contain config file for sitemap. (simple_sitemap.bundle_settings.node.govcms_…). But the module itself is not enabled after installation.

### Steps to reproduce
* Install the site and enable all optional modules for content types.
* Export the config.
* Do a simple update in config file e.g. change the site "name" in "system.site.yml"
* Import the config
* It will complain about Simple XML Sitemap module not installed after import with list of config files which requires it.

### Solution
All these optional content types modules should have Simple XML Sitemap as a dependency.

**Comment by tobywildopc** [comment]
The other option is to remove the config for Simple Sitemap.
The config options that exist for all of them is just:

<code>
index: 1

priority: '0.5'
</code>

What would be the better option?  Removing the config or adding a module dependency?

**Comment by petrillek** [comment]
I think sitemap generation is often a requirement so for me its better to have the dependency out of the box.

**Comment by brett-sargeant** [comment]
definitely required

**Comment by simesy** [comment]
Fixed
