### ISSUE TITLE
Module Suggestions

### ISSUE THREAD

**Issue by OPCIT** [govCMS/govcms8-installer#108]
Hi Guys,

After installing and testing the govcms8 distro we have a few potential suggestions for modules that we use regularly that are in the D7 distro.

* Rules
* Better Exposed Filters
* Easy Breadcrumb (in lieu of Crumbs not having a D8 option)
* Views Bulk OPerations
* Chosen  /  Simple Hierarchical Select (SHS not in Govcms7)

Could these modules be potentially investigated as additions to the GovCMS8 Distro? Also, what is your stance on including modules currently in Alpha?

Cheers

Jeannie Panting

**Comment by tobybellwood** [comment]
Thanks Jeannie - we'll have a look through those suggestions.

Alpha isn't a concern, as long as the module is under development and has a plan to get out of Alpha sometime soon (and thus into Security coverage!)

**Comment by OPCIT** [comment]
Wonderful thanks for that Toby.

**Comment by murraywoodman** [comment]
Here is our wishlist.

**responsive_favicons**
Allows favicons to be uploaded and served for  site. Essential when you have a single theme, such as uikit_starter which has its own "default" favicon. This allows custom favicons to work without the need to edit the theme.
Priority: High

**menu_block**
Allows for fine grained control over the level of the menu to be displayed. Required when you want the menu to "follow down" as the user goes deeper into the hierarchy.
Priority: High

**twig_tweak**
Gives ability to embed things inside twig templates. This could be a get out of gaol free card for SaaS sites.
Priority: High

**easy_breadcrumb**
We agree that this would be a good addition. Possible to configure breadcrumbs when needed.
Priority: Medium

**smart_trim**
Better summary text for node teasers and description for editors who do not provide custom text.
Priority: Medium

**ckeditor_responsive_plugin**
Allows grids to be embedded into the WYSIWYG. This can be handy when the editor is looking for a simple way to get some structure into the WYSIWYG.
Priority: Low

**Comment by petrillek** [comment]
One more to the list:

**extlink**
Automatically marks outgoing or mailto links with an icon. Can open them in new window. Show a confirmation message about leaving a site etc.

**Comment by murraywoodman** [comment]
**csv_serialization**
Works with RESTful Web Services module and Views. Provides the ability to serialise data to CSV. Having data avialable in this format will be a big boost for generic decoupled components which are able to work with CSV data. For example, a chart or statistic widget could consume a CSV produced by Views and CSV Serialization. This is a very easy on ramp for JS based components. It is true that XML and JSON are available already, however, these formats do not have a data model which is as regular as CSV requiring some translating code. CSV is a known shape and this makes it easier to write components which consume it. This module is stable and has a lot of downloads.
https://www.drupal.org/project/csv_serialization

PS. Re extlink - this can be implemented easily enough in the theme.

**Comment by murraywoodman** [comment]
**media_entity_download**
On more than one project we have had government clients be disappointed on not being able to update the contents of a PDF when it needs to be changed. FIles such as this are usually cached for a long period (2 weeks) and cannot be changed on disk due to the way Drupal handles Media. Oftentimes editors will want to link users straight to the file version of a Media entity, rather than to the Media entity page. eg. with inline links in the WYSIWYG. If they do link to the PDF, and it is bookmarked or cached, it is not possible to easily get an update to the user. The best solution is to use Media Entity Download which can provide a download path to the freshest version of a file (/media/X/download). This module doesn't have so many installs but it seems to be a vital fix for a problem clients will tend to have when they have compliance issues around being able to update documents such as PDFs.
https://www.drupal.org/project/media_entity_download

**Comment by OPCIT** [comment]
Is there any plan for a simple TOC (Table of Contents) module to be implemented:

- https://www.drupal.org/project/toc_filter
- https://www.drupal.org/project/toc_js

If not what the preferred method...... themed or manual?

**Comment by OPCIT** [comment]
Another common function for many smaller sites.

Sitemap: https://www.drupal.org/project/sitemap (8.x-1.4)

**Comment by simesy** [comment]
[fieldblock](https://www.drupal.org/project/fieldblock) - Basic use-case is to make field values available as blocks and placed in regions. We use it for some nice site building techniques.

[dynamic_entity_reference](https://www.drupal.org/project/dynamic_entity_reference) - Self-evident I assume. I think this has high value.

[allowed_formats](https://www.drupal.org/project/allowed_formats) - Gives us much better control over what formats are available, often simplifying the editor experience.

[diff](https://www.drupal.org/project/diff) - Classic diff. Diff all the revisionable things.

**Comment by simesy** [comment]
Of the other requests, I second the following: easy breadcrumb, better exposed filters, sitemap(!), twig_tweaks, menu_block.

From OPCIT's list, looks like `chosen` is already in.

**Comment by murraywoodman** [comment]
@OPCIT For the TOC requirement we have implemented that in the theme via Anchorific. It works pretty well.

**Comment by simesy** [comment]
Added "allowed_formats" to my list above.

**Comment by OPCIT** [comment]
@murraywoodman I'm always in two minds about making users jump into the theme code when there are supported modules already out there that do a great job. The Anchorific JS library is pretty good, but it still needs a level of knowledge and configuration for it to work.

I think that common functions like a TOC should be part of the base distro with easy to use off/on control.

**Comment by murraywoodman** [comment]
> **responsive_favicons**
> Allows favicons to be uploaded and served for site. Essential when you have a single theme, such as uikit_starter which has its own "default" favicon. This allows custom favicons to work without the need to edit the theme.

Not Needed. There is a Favicons module for Metatag.

**Comment by simesy** [comment]
I've added diff module to our list... Not sure how other people offer this feature, I've always found it useful.

**Comment by petrillek** [comment]
> > **responsive_favicons**
> > Allows favicons to be uploaded and served for site. Essential when you have a single theme, such as uikit_starter which has its own "default" favicon. This allows custom favicons to work without the need to edit the theme.
> 
> Not Needed. There is a Favicons module for Metatag.

For the Metatag you need a way how to upload the actual files to the server. If done via Media entity editors can accidentaly delete/overwrite them. Direct file upload is usually tied to some entity.

**Comment by OPCIT** [comment]
Any solution suggestions for a dynamic menu such as Superfish?

We are going to need this dynamic drop-down menu functionality at some point, as a good percentage of sites use it.

**Comment by simesy** [comment]
Closing in favour of the module request form https://github.com/govCMS/govCMS8/issues/new/choose

Note that the new modules get added glacially now due to it being a large distribution already which has overhead.
