### ISSUE TITLE
Remote video

### ISSUE THREAD

**Issue by petrillek** [govCMS/govcms8-installer#118]
The media bundle remote_video (using the field_media_video_embed_field) is now clashing with a media bundle remote_video (using the field_media_oembed_video) introduced in Drupal 8.6. It can lead to unexpected behaviour for users. We recommend to change the GovCMS config so it only add the tags field to the Core remote video bundle.

**Comment by pandaskii** [comment]
@petrillek Can you list the steps to replicate the issue? thanks

**Comment by gargsuchi** [comment]
field_media_oembed_video - this field is defined only in the standard and the demo_umami profile. 
remote_video - this media bundle is defined on demo_umami on install, and in standard profile as optional. 
But in govCMS, you will be installing the govcms profile. So I don't think there should be any clash.

**Comment by murraywoodman** [comment]
I would ask that this issue be looked at closely as it is causing us some difficulties. The Modifiers module, which is in GovCMS8, supports the Media configuration which ships with the standard profile. The assumption there is that the remote_video bundle will be implemented with the core field field_media_oembed_video. In GovCMS8 the remote_video bundle is implementing it differently. Strictly speaking this is OK, however, in practice it is causing problems.

How can this issue be replicated? At the moment it cannot easily but here goes...  If a Modifier plugin (implemented in the theme layer) needs to support "remote_video" the Modifier module will assume that it is using the core approach, not the video_embed_field. This effectively breaks the modifier. ie. the video will not be discovered and will not display. This is not a problem for GovCMS8 out of the box, but it can be a problem if themers implement a Modifier with video as it is defined currently.

**Media in core**

Now that Media is stable in core, it would be expected that GovCMS8 moves with the times and adopts it as the preferred way of handling media. This would mean that the contrib module video_embed_field could be removed from the distro. This simplification of the platform is a strong argument for making this change. Now is a crucial time for the distro as it is still in Alpha and a change such as this is acceptable.

The option is always open for site builders to switch to the core way of handling Media. There are two downsides to this:

1. Dependencies

The dependencies mean that it cannot be uninstalled.

govcms_content_types -> govcms_media -> video_embed_field
govcms8_foundations -> govcms8_modifiers -> govcms_media -> video_embed_field

Media is deep down the hierarchy. Switching off video_embed_field will flow through all the way up to govcms_content_types.

2. Media is an important system

The govcms_media module ships with logic and config. It is likely that the GovCMS team will want to iterate on this in the future. It would be nice if site builders didn't have the need to upset this config.

**Suggestion**

Uninstall the module
Implement the remote_video bundle with oembed.
Tweak the bulk upload functionality on govcms_media to be aware of the new field.

**Knock on effects**

Changing the way media is handled will have a knock on effect. Sites which have been built with the Alpha release will continue on with the old video_embed_field and therefore will need this module to be part of the distro. It would not be advisable to remove it as this will badly break current sites... As the distro is Alpha, it still is possible.

**Comment by simesy** [comment]
Fixed per above
