### ISSUE TITLE
Module suggestion: ckeditor_templates

### ISSUE THREAD

**Issue by rooby** [govCMS/govcms8-installer#120]
It would be good to be able to use the [ckeditor_templates ](https://www.drupal.org/project/ckeditor_templates) module.

Equivalent functionality was available in the D7 version of GovCMS.

**Comment by rooby** [comment]
Optionally, there is a module for managing templates via the UI - [ckeditor_templates_ui](https://www.drupal.org/project/ckeditor_templates_ui), which was not available in the D7 GovCMS.

**Comment by murraywoodman** [comment]
I think something like this would be very helpful. In another issue I made a low priority suggestion for ckeditor_responsive_plugin but upon reflectioon going for something more general like this would be better. There are some UI Kit components which would be well suited to this kind of approach (grids, keyword list, progress indicator, alerts, callouts, etc). If this module were adopted a standard set of templates could be developed to use it. NB. I haven't actullay used the module can't really comment on its efficacy. The concept is good though.

**Comment by gargsuchi** [comment]
Or maybe this module - https://www.drupal.org/project/wysiwyg_template

**Comment by simesy** [comment]
+1 to wysiwyg_template

**Comment by Belhendo** [comment]
Hi all, apologies for the lack of response from us on this one. If you're interested in a wysiwyg_template, could you please complete the new module request template here, create a new issue with it and we can review it and respond: https://github.com/govCMS/govCMS8/blob/1.x/.github/ISSUE_TEMPLATE/module-request.md

Thank you!

**Comment by simesy** [comment]
See #440
