### ISSUE TITLE
Simplify Panelizer uninstall

### ISSUE THREAD

**Issue by petrillek** [govCMS/govcms8-installer#132]
As a developer I would like to have easier option to uninstall Panelizer module, but still have the GovCMS8 Foundations module enabled.

### The issue
There is a panelizer field storage config inside GovCMS8 Foundations which needs the Panellizer dependency.

### Solution
Move the panelizer field storage config to govcms_content_types module, where it make more sense as it is closely tied to the content types.

**Comment by petrillek** [comment]
There is a second commit in the PR as I realize there are other two field sotrages related to content types so I moved them as well.

**Comment by simesy** [comment]
Fixed(?)
