### ISSUE TITLE
"Styleguide" link in main nav leads to 404

### ISSUE THREAD

**Issue by klonos** [govCMS/govcms8-installer#148]
The link points to `themes/contrib/govcms8_uikit_starter/styleguide` ...not sure if this was meant to be linking to the page generated by https://www.drupal.org/project/styleguide but I don't see that module in the distro.

![screen shot 2018-11-21 at 1 25 53 pm](https://user-images.githubusercontent.com/2423362/48815008-0e414700-ed91-11e8-8a2e-e0edda7c7fb0.png)

**Comment by tobybellwood** [comment]
ah - the styleguide is only enabled if the govcms8_default_content module is also enabled...

**Comment by klonos** [comment]
Yep. Still, should either be removed, or fixed so that it does not 404.
