### ISSUE TITLE
Module Suggestion - Menu Block

### ISSUE THREAD

**Issue by gargsuchi** [govCMS/govcms8-installer#169]
I know this is already suggested here - #108
But since that one has too many module suggestions, creating this issue for just the https://www.drupal.org/project/menu_block inclusion.

The blocks for menus in Drupal Core are very basic. They are not very configurable.   
menu_block provides with configurable blocks of menu with advanced features. This kind of functionality is very useful for eg: in cases where we need to show a relevant set of menus links in sidebar, menu_block is an extremely useful module.

**Comment by fubarhouse** [comment]
Could we please start discussions around use cases?

A one-liner business case with a set of pros/cons. The primary reason for this is that a significant amount of functionality has made it to core and the functionality produced in this module would not translate to breadcrumbs (in core) which would degrade the user experience in navigation. It would also fragment standard process to achieving the same result which isn't a problem but it would be if it happens repeatedly.

I am all for the change, however some discovery needs to be done to determine exactly what it provides as alternative to core functionality and how widespread those limited features would be in demand.

This is an open discussion, so anybody who can contribute short business case with well-defined pros and cons are welcome.

**Comment by petrillek** [comment]
One usecase for this module is as follows.
Imagine there is a top level menu item "News", it has few subpages ("Latest news", "All news", "Best News"…) these pages have a Views on them listing the News nodes.
With core menu block I'm able to show the submenu tree on these pages, because they are part of the menu. 
But then I open one of the actuall News, which is not in the menu, and it will be good for consistent UX to show the submenu as well.
For that I would like to use the Menu block feature, where I can precisely set the exact starting item of the menu block, not only the level. Then I can pplace this block on the news content type.

Pros – more consitent UX even on pages which are not in the menu.
Cons – cannot think of any at this time.

**Comment by joshua-graham-adelphi** [comment]
Any one know why this module is in the composer.json file here but not on the lagoon images used for production ?

**Comment by tobybellwood** [comment]
@joshua-graham-adelphi it is - I double checked on our d8 site and a fresh build?
```
[govcms8-saas]cli-drupal:/app$ composer show drupal/menu_block
name     : drupal/menu_block
descrip. : Provides configurable blocks of menu links.
keywords :
versions : * 1.5.0 
```

if it's for a govcms agency, drop a service desk ticket in and we can check?

**Comment by brett-sargeant** [comment]
IIRC it's not enabled, but is in the available list on the default install, unless that has changed in a recent update

**Comment by joshua-graham-adelphi** [comment]
I'm cloning from govcms8-scaffold - master branch, maybe I did something wrong, as it definitely not in my build - built today. hmm

> [govcms8-saas]cli-drupal:/app$ composer show drupal/menu_block
>
>  [InvalidArgumentException]
>  Package drupal/menu_block not found
>
> show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [--ignore IGNORE] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>]

Full build commands used:

user@joshg-pc-dev MSYS /c/Projects/drupal_projects
> $ git clone https://github.com/govCMS/govcms8-scaffold.git govcms8-scaffold-menublock-test
> Cloning into 'govcms8-scaffold-menublock-test'...
> remote: Enumerating objects: 52, done.
> remote: Counting objects: 100% (52/52), done.
> remote: Compressing objects: 100% (38/38), done.
> remote: Total 268 (delta 20), reused 36 (delta 11), pack-reused 216
> Receiving objects: 100% (268/268), 336.38 KiB | 121.00 KiB/s, done.
> Resolving deltas: 100% (121/121), done.
> 
> user@joshg-pc-dev MSYS /c/Projects/drupal_projects [2019-08-28 10:29:05]
> $ cd govcms8-scaffold-menublock-test/
> 
> user@joshg-pc-dev MSYS /c/Projects/drupal_projects/govcms8-scaffold-menublock-test (develop)
> $ # fresh build
> 
> user@joshg-pc-dev MSYS /c/Projects/drupal_projects/govcms8-scaffold-menublock-test (develop)
> $ docker-compose rm
> No stopped containers
> 
> user@joshg-pc-dev MSYS /c/Projects/drupal_projects/govcms8-scaffold-menublock-test (develop)
> $ docker-compose down
> Removing network govcms8-scaffold-menublock-test_default
> WARNING: Network govcms8-scaffold-menublock-test_default not found.
> Network amazeeio-network is external, skipping
> 
> user@joshg-pc-dev MSYS /c/Projects/drupal_projects/govcms8-scaffold-menublock-test (develop)
> $ docker-compose up -d --build
> Creating network "govcms8-scaffold-menublock-test_default" with the default driver
> Building cli
> Step 1/4 : FROM govcms8lagoon/govcms8
>  ---> f2b937fe1d7d
> Step 2/4 : COPY themes/ /app/web/themes/custom
>  ---> Using cache
>  ---> 6fd7347c9fcf
> Step 3/4 : COPY config /app/config
>  ---> Using cache
>  ---> 1d5b79d1a1fd
> Step 4/4 : COPY favicon.ico /app/web
>  ---> Using cache
>  ---> c8a298756f4f
> 
> Successfully built c8a298756f4f
> Successfully tagged govcms8-saas:latest
> Building test
> Step 1/6 : FROM govcms8lagoon/test
>  ---> 8ddeedd1ad30
> Step 2/6 : COPY themes/ /app/web/themes/custom
>  ---> Using cache
>  ---> ab1b1eff53a8
> Step 3/6 : RUN rm -Rf /app/tests/behat/features/*
>  ---> Using cache
>  ---> 805c3f119ae7
> Step 4/6 : COPY tests/behat/features/ /app/tests/behat/features
>  ---> Using cache
>  ---> cf8566a36dab
> Step 5/6 : RUN rm -Rf /app/tests/phpunit/tests/*
>  ---> Using cache
>  ---> 5c0b5530bead
> Step 6/6 : COPY tests/phpunit/tests/ /app/tests/phpunit/tests
>  ---> Using cache
>  ---> 86a379e8ecb9
> 
> Successfully built 86a379e8ecb9
> Successfully tagged govcms8-scaffold-menublock-test_test:latest
> Building nginx
> Step 1/4 : ARG CLI_IMAGE
> Step 2/4 : FROM ${CLI_IMAGE} as cli
>  ---> c8a298756f4f
> 
> Step 3/4 : FROM govcms8lagoon/nginx-drupal
>  ---> da028729a4cb
> Step 4/4 : COPY --from=cli /app /app
>  ---> Using cache
>  ---> eff3b77a09f7
> 
> Successfully built eff3b77a09f7
> Successfully tagged govcms8-scaffold-menublock-test_nginx:latest
> Building php
> Step 1/4 : ARG CLI_IMAGE
> Step 2/4 : FROM ${CLI_IMAGE} as cli
>  ---> c8a298756f4f
> 
> Step 3/4 : FROM govcms8lagoon/php
>  ---> 3cf2f1275ee2
> Step 4/4 : COPY --from=cli /app /app
>  ---> Using cache
>  ---> d8a893054513
> 
> Successfully built d8a893054513
> Successfully tagged govcms8-scaffold-menublock-test_php:latest
> Creating govcms8-scaffold-menublock-test_mariadb_1 ... done
> Creating govcms8-scaffold-menublock-test_cli_1     ... done
> Creating govcms8-scaffold-menublock-test_test_1    ... done
> Creating govcms8-scaffold-menublock-test_php_1     ... done
> Creating govcms8-scaffold-menublock-test_nginx_1   ... done
> Creating govcms8-scaffold-menublock-test_chrome_1  ... done
> 
> user@joshg-pc-dev MSYS /c/Projects/drupal_projects/govcms8-scaffold-menublock-test (develop)
> $ docker-compose exec test bash
> [govcms8-saas]cli-drupal:/app$ ls -lsha web/modules/contrib | grep menu_block
> [govcms8-saas]cli-drupal:/app$ composer show drupal/menu_block
> 
>   [InvalidArgumentException]
>   Package drupal/menu_block not found
> 
> show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [--ignore IGNORE] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>]
> 
> [govcms8-saas]cli-drupal:/app$

**Comment by joshua-graham-adelphi** [comment]
Never-mind, need to run docker pull, but now the cli image has an issue. I'll add a PR to note for others in the scaffold repo.

> $ docker-compose pull
> Pulling cli     ... error
> Pulling test    ... done
> Pulling nginx   ... done
> Pulling php     ... done
> Pulling mariadb ... done
> Pulling chrome  ... done
> 
> ERROR: for cli  pull access denied for govcms8-saas, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ERROR: pull access denied for govcms8-saas, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by tobybellwood** [comment]
if in doubt `docker-compose build --no-cache && docker-compose up -d` should grab freshies and force a rebuild, and then bring it all up

**Comment by joshua-graham-adelphi** [comment]
> docker-compose build --no-cach
It appears this does not update the best layer image :-(

@see https://stackoverflow.com/questions/52664744/does-docker-build-no-cache-actually-download-and-refresh-the-base-image

Can you have a look at https://github.com/govCMS/govcms8-scaffold/issues/19 ? can't pull cli image

**Comment by fubarhouse** [comment]
@joshua-graham-adelphi,

That's a separate issue, see my response in that ticket.

Just because the base images are updated does not mean the container will have its image updated. In the event you need to forcibly update the set of containers:

1. Take a backup of the database
2. Run `docker-compose kill && docker-compose up -d` Some people use `docker-compose restart` or `ahoy restart` however personally I've had mixed results with that - but it wouldn't require a database dump.
3. Reimport database

An image is like a VM image - it's a starting point. By updating an image after starting a set of containers, your containers will not update until they are essentially re-based from the new image. What the mechanism above does is essentially a local redeployment of the site which does rebase the containers from the new images.
