### ISSUE TITLE
Adding components module

### ISSUE THREAD

**Issue by simesy** [govCMS/govcms8-installer#17]
Pattern libraries (aka styleguides, living styleguides, component libraries) are becoming increasingly popular, because they:

- allow re-usability of (eg) twig/css across multiple applications
- enable design sign-off prior to build

Here's a prezzo about it. https://www.youtube.com/watch?v=quK0-tgL16s

The problem with adding arbitrary twig libraries to Drupal is they are not automatically discoverable. To make them discoverable/usable, the defacto standard is the Components module: http://drupal.org/project/components

The request is to add http://drupal.org/project/components module to enable integration with twig-based pattern libraries out of the box.

**Comment by simesy** [comment]
@febdao and I have done a bit of work with Patternlab. But the same dependency applies to integration with KSS Node.

And check out this tutorial https://www.previousnext.com.au/blog/reusable-style-guide-components-using-field-formatters-and-twig-embed

**Comment by tobybellwood** [comment]
Thanks @simesy - We'll have a look in the next D8 sprint

**Comment by simesy** [comment]
This got added I think
