### ISSUE TITLE
Upgrade Display Suite module

### ISSUE THREAD

**Issue by gargsuchi** [govCMS/govcms8-installer#182]
One of my installs has started showing up these warnings when I visit the Manage Display of content types/ paragraph types

`Warning: Illegal offset type in isset or empty in _ds_field_ui_table_layouts() (line 719 of modules/contrib/ds/includes/field_ui.inc).
_ds_field_ui_table_layouts('paragraph', 'landing_page_first_banner', 'default', Array, Object) (Line: 42)
ds_field_ui_fields_layouts(Array, Object) (Line: 247)
ds_form_entity_view_display_edit_form_alter(Array, Object, 'entity_view_display_edit_form') (Line: 539)
Drupal\Core\Extension\ModuleHandler->alter('form', Array, Object, 'entity_view_display_edit_form') (Line: 834)
Drupal\Core\Form\FormBuilder->prepareForm('entity_view_display_edit_form', Array, Object) (Line: 276)
Drupal\Core\Form\FormBuilder->buildForm('entity_view_display_edit_form', Object) (Line: 93)`

This is an issue in the ds issue queue here - https://www.drupal.org/project/ds/issues/2875412

Solution - Upgrade ds module from 3.1 to 3.2

**Comment by gargsuchi** [comment]
Realized that there is already a PR for this - https://github.com/govCMS/govCMS8/pull/172

**Comment by OPCIT** [comment]
Any news on the release update?

**Comment by fubarhouse** [comment]
@OPCIT,

We have a series of modules to test including this one referenced by the PR.
There's no formal date which we can advise, however it won't be long.

**Comment by OPCIT** [comment]
Thanks Carl. 

Moving forward, is there any plan for govCMS to set scheduled periods (ie first Monday of the month) when updates to the distro/environment will occur.

One of the problems with the previous version of govCMS was not knowing when things where going to be patched or released.

**Comment by fubarhouse** [comment]
@OPCIT,

The plan is to have something in place.

However, there's no telling to when this could or in fact will happen - as nothing is decided right now.

**Comment by OPCIT** [comment]
Thanks Karl. Having something in place will certainly help us (and I imagine others) when developing new projects.

**Comment by OPCIT** [comment]
Any update on this?

**Comment by fubarhouse** [comment]
@OPCIT,

It will be included in the beta release which is undertaking testing at the moment, however there's no release date yet.

**Comment by fubarhouse** [comment]
Resolved in #172
