### ISSUE TITLE
Embed Video into a page

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#2]
_From @pandaskii on September 20, 2017 5:0_

**As a content editor**

I want to embed the YouTube video into a page and the video autoplay has to be disabled by default when inserting media into the WYSIWYG. So that people looking at my page don't get bombarded by content they haven't chosen to view

_Copied from original issue: govCMS/govCMS8-core#1_

**Comment by pandaskii** [comment]
Resolved by video_embed_field module in distribution
