### ISSUE TITLE
Module suggestion - Config ignore

### ISSUE THREAD

**Issue by petrillek** [govCMS/govcms8-installer#207]
_As an editor I want to do changes and create new webforms without changing the site configuration._

I’ve set up a config split for `webform.webform.*`.  That is working fine for existing webforms, but newly created webform is deleted after running config import (through UI or with drush) unless it is “exported” first. 
It is in accordance with the discussion here: https://www.drupal.org/project/config_split/issues/2861266. 
They are proposing to use Config ignore module (https://www.drupal.org/project/config_ignore) to solve this issue.
Can this module be considered for addition, or there exist a way how to solve it without it?

**Comment by pameeela** [comment]
+1 to this! Badly needed for webforms.

**Comment by petrillek** [comment]
Hi @pameeela ;),
leave your vote here: https://community.govcms.gov.au/t/calling-for-community-contributions-to-drupal8-module-discussion/1570

**Comment by thisisalistairsaccount** [comment]
Config Ignore was added to GovCMS 8 as part of 1.0.0-beta4 in April 2019 - https://github.com/govCMS/GovCMS8/releases/tag/1.0.0-beta4

Current version as of 22 Oct 2020 is 2.1
