### ISSUE TITLE
Module Suggestions - Compiled LIst

### ISSUE THREAD

**Issue by OPCIT** [govCMS/govcms8-installer#215]
List of modules suggestions so far:

- https://www.drupal.org/project/toc_js
- https://www.drupal.org/project/config_ignore
- https://www.drupal.org/project/menu_block
- https://www.drupal.org/project/superfish
- https://www.drupal.org/project/better_exposed_filters
- https://www.drupal.org/project/ckeditor_templates
- https://www.drupal.org/project/ckeditor_templates_ui
- https://www.drupal.org/project/ckeditor_responsive_plugin
- https://www.drupal.org/project/wysiwyg_template
- https://www.drupal.org/project/rules
- https://www.drupal.org/project/easy_breadcrumb
- https://www.drupal.org/project/views_bulk_operations
- https://www.drupal.org/project/shs
- https://www.drupal.org/project/responsive_favicons
- https://www.drupal.org/project/twig_tweak
- https://www.drupal.org/project/smart_trim
- https://www.drupal.org/project/extlink
- https://www.drupal.org/project/csv_serialization
- https://www.drupal.org/project/media_entity_download
- https://www.drupal.org/project/sitemap
- https://www.drupal.org/project/fieldblock
- https://www.drupal.org/project/dynamic_entity_reference
- https://www.drupal.org/project/allowed_formats
- https://www.drupal.org/project/diff
- https://www.drupal.org/project/easy_social

Can people +1 for those modules you'd like to see added in the next release.

**Comment by OPCIT** [comment]
+1 Toc JS
+1 Menu Block
+1 Superfish
+1 Sitemap
+1 Easy Social
+1 Rules

**Comment by tobybellwood** [comment]
I've created a post and poll over at https://community.govcms.gov.au/t/calling-for-community-contributions-to-module-discussion/1570 if you want to contribute there too

**Comment by jaypan** [comment]
I voted in the poll over there, but I'd like to propose the Advanced CSS/JS Aggregation module. I don't generally build sites without it. https://www.drupal.org/project/advagg

**Comment by gargsuchi** [comment]
+1 Toc JS
+1 Menu Block
+1 Sitemap
+1 Rules
+1 Config Ignore
+1 Better exposed filters

**Comment by simesy** [comment]
Closing in favour of the module request form https://github.com/govCMS/govCMS8/issues/new/choose

Note that the new modules get added glacially now due to existing governance (and sometimes performance) overhead of a large distribution.
