### ISSUE TITLE
Error: Call to a member function getPattern() on null in Drupal\panels

### ISSUE THREAD

**Issue by OPCIT** [govCMS/govcms8-installer#216]
When editing panel content get error: Error: Call to a member function getPattern() on null in Drupal\panels

https://www.drupal.org/project/panels/issues/3031778 suggests rolling recent CTools update back  to 8.x-3.0.0.

Tested on local composer install and fixes the issue,

**Comment by murraywoodman** [comment]
Yes, we can confirm this is a bug which will break Panelizer UI quite badly. Site builders will not be able to edit blocks and configure the on the Content tab.

Rolling Chaos Tool Suite back to 3.0 will work. There appears to be no DB updates in CTools 3.1 (after a quick check).

Applying these two patches also works with Chaos Tool Suite 3.1.

```
            "drupal/panels": {
                "https://www.drupal.org/project/panels/issues/3031778#comment-12980944": "https://www.drupal.org/files/issues/2019-02-21/panels_tempstore-updated-3031778-37.patch"
            },
            "drupal/panelizer": {
                "https://www.drupal.org/project/panelizer/issues/3034080#comment-12978299": "https://www.drupal.org/files/issues/2019-02-19/panelizer_temp_store-3034080-03.patch"
            },
```
Thanks @radimklaska for testing these.

New installs and updates of GovCMS8 for the last 13 days will be broken. This is serious and should be fixed quickly @tobybellwood 

We would hope that Panels and Panelizer will catchup to CTools.
https://www.drupal.org/node/2935639
https://www.drupal.org/project/drupal/issues/2935617

For now now sticking to CTools 3.0 would easiest.

**Comment by tobybellwood** [comment]
@murraywoodman - we can't get a rollback to 3.0.0 to work?

**Comment by murraywoodman** [comment]
Hi @tobybellwood Sorry for the delay in replying. Please provide some details of the troubles you are having and we will take a look into it. We have gone down the route of applying the patches on other sites and that has worked OK. In the meantime we will roadtest the 3.0 route and see if anything crops up.

**Comment by tobybellwood** [comment]
it's ok - I think we've fixed it - turns out it was a local issue - we're locking ctools to 3.0.0 in #249 until the panels/panelizer patches turn into releases.

**Comment by OPCIT** [comment]
In a recent build which used the following out-of-the box modules:
- CTools: 8.x-3.0
- Panelzer: 8.x-4.1
- Panels: 8.x-4.4

I found that I had to role back Panels to 8.x-4.3 in order to get the following to work without error:

Structure > Content Types > Standard page > Manage display > Full content > Sidebar Right (2:1) > Edit > Content
