### ISSUE TITLE
As a contributor, I want to be able to suggest new modules (or upgrades) as easily as possible

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#23]
On the 1.x branch, we should remove the composer.lock file (this is created in Travis anyway).  This will enable a wider section of the community to be able to suggest enhancements, and have those suggestions tested and verified automatically.

**Comment by simesy** [comment]
composer.lock is removed. New module request process and module update processes exist. Issues can be created to escalate module updates.
