### ISSUE TITLE
Fatal exception for search with google analytics

### ISSUE THREAD

**Issue by rob3000** [govCMS/govcms8-installer#242]
Possibly could be fixed from https://github.com/govCMS/govCMS8/pull/230 but currently when database search and google analytic for search is enabled a fatal exception is thrown when there are no matches for that given search request. If there are results found for that search then it all works fine. 

i've logged a patch here: https://www.drupal.org/project/google_analytics/issues/3021119 and have added steps to reproduce.

**Comment by gargsuchi** [comment]
@rob3000  I can replicate the error, but it seems that the patch you provided on d.o still has the same error.
I have added another patch in the issue queue which works.

**Comment by gargsuchi** [comment]
The patch applied [here](https://github.com/govCMS/govCMS8/pull/186) actually fixes the bug. 
But just applying the patch in the make file is not enough. 
@tobybellwood We need to enable patching in composer.json AND composer-lagoon.json. 
eg: PR - https://github.com/govCMS/govCMS8/pull/239

**Comment by rob3000** [comment]
This looks to have now been fixed:
I can see https://github.com/govCMS/govCMS8/pull/186/files has been merged and is in the 1.x branch https://github.com/govCMS/govCMS8/blob/1.x/drupal-org.make#L60
