### ISSUE TITLE
Access denied on home page after enabling govcms8_default_content

### ISSUE THREAD

**Issue by klonos** [govCMS/govcms8-installer#248]
**Steps to reproduce**

1. Install fresh (current version at time of writing is 1.0.0-beta2)
2. Enable the "GovCMS 8 Default Content" module
3. Visit the site as anonymous -> Access denied 👎 
4. Grant "View any unpublished content" permission to anonymous users
5. Visit the site as anonymous -> works 👍 
6. Revoke "View any unpublished content" permission from anonymous users
7. Edit the "GovCMS8 Starter" page -> notice how it's set to draft
8. Set to "Needs review", then set to "Published"
9. Visit the site as anonymous -> works 👍 

Furthermore, all the pages linked from the footer menu are also set to draft, which causes the entire footer to be missing when viewing the home page as anonymous.

Same goes for all the nodes listed in the "Content example (demo)" section.

**Expected behavior**

When a person is demoing a fresh installation of GovCMS8 after having enabled the govcms8_default_content module, they should not get "access denied" on the front page, and all demo components should be accessible by anonymous users.

The "GovCMS8 Starter" page and all the demo content listed or linked to from the home page should be published OOTB when the "GovCMS 8 Default Content" module is enabled, so that all the features of the demo home page can be viewed by anonymous users.

List of nodes that need to be set to published OOTB:

- /homepage
- /about-us
- /accessibility
- /copyright
- /disclaimers
- /privacy-statement
- /blog/example
- /event/example
- /news-and-media/example
- /freedom-of-information/example
- /standard-page-example

**Comment by tobybellwood** [comment]
ah yes - the step that creates all this content was all developed before we added content moderation to the distro!

**Comment by klonos** [comment]
Need a GovDEX ticket for this @tobybellwood ?

**Comment by gargsuchi** [comment]
Created a govdex ticket  @klonos  @tobybellwood

**Comment by gargsuchi** [comment]
Update: @klonos  
The govdex ticket for this one has been done. Hopefully should be fixed in the next release.

**Comment by gargsuchi** [comment]
@klonos This should be fixed now. 
@tobybellwood Should we close this issue?

**Comment by tobybellwood** [comment]
closing - merged in 1.0-beta4 release
