### ISSUE TITLE
Failed to create config directory /app/config/default 

### ISSUE THREAD

**Issue by HurricaneInteractive** [govCMS/govcms8-installer#251]
Getting the following error when trying to export my config using `ahoy cex` or `ahoy drush cex`.

Haven't made any changes to the export path for the config, and I still have the config folder in my project. Site setup with docker.

**Comment by stooit** [comment]
Two things to check here:

1. Docker File Sharing includes a path containing your codebase
2. Codebase files are owned by your local user and you are not running as root

**Comment by gargsuchi** [comment]
@HurricaneInteractive  Are you still facing this error?

**Comment by HurricaneInteractive** [comment]
Running `ahoy build` fixed this issue
