### ISSUE TITLE
Devel causing website to break

### ISSUE THREAD

**Issue by purencool** [govCMS/govcms8-installer#257]
Devel is breaking page because of a routing issue. To recreate this error doing the following,  

**The process to recreate the issue:**  
1. `composer create-project --stability dev --prefer-dist govcms/govcms8-project www`   
2. `cd www`  
3. `composer require drupal/devel `  
4. Then installed the website
5. `../vendor/drush/drush/drush en devel`
6. `../vendor/drush/drush/drush cr`

**The error that displayed:**  
Then I navigated to the front page of the website in the browser, the image below shows the error.  

![Screenshot of govcms local_blog](https://user-images.githubusercontent.com/621875/54583440-479c7180-4a68-11e9-837d-e6063e03c098.jpg)

**Solution**
Either update to admin_toolbar 8.x-1.26 using composer or add the following patch   
https://www.drupal.org/project/admin_toolbar/issues/3009193#comment-12950604

The result I got was the following,
![Screenshot of Blog _ aaaa](https://user-images.githubusercontent.com/621875/54583604-cee9e500-4a68-11e9-99d5-1435debdc761.jpg)

**Comment by gargsuchi** [comment]
Hi @purencool 
Thanks for reporting this error and providing a fix.
I have created a govdex ticket for n upgrade of admin_toolbar module - which will fix this issue. 
Will keep you updated.

Thanks.

**Comment by thisisalistairsaccount** [comment]
reviewing older issues. admin_toolbar is @ 2.3 and this should no longer be an issue
