### ISSUE TITLE
Module Suggestion - SVG Image

### ISSUE THREAD

**Issue by gargsuchi** [govCMS/govcms8-installer#261]
https://www.drupal.org/project/svg_image

**Comment by Belhendo** [comment]
Hi gargsuchi

Apologies for the delay in responding here. If you would like GovCMS to consider the inclusion of a module into the distro, please complete the template at the link below and create a new issue for the request. 

https://github.com/govCMS/govCMS8/blob/1.x/.github/ISSUE_TEMPLATE/module-request.md 

Thanks
