### ISSUE TITLE
Security modules not present - will CSP and HSTS be included in GovCMS core build?

### ISSUE THREAD

**Issue by MikeGlew** [govCMS/govcms8-installer#300]
ISM Security Control: 1424; Revision: 2; Updated: Sep-18; Applicability: O, P, S, TS; Priority: Should
Web browser-based security controls are implemented for web applications in order to help protect both web applications and their users.

IS there any reason why these are not included in the base build?

**Comment by MikeGlew** [comment]
https://www.drupal.org/project/csp
https://www.drupal.org/project/hsts

**Comment by tobybellwood** [comment]
Hi @MikeGlew - we enforce HSTS for all sites on the GovCMS platform - we have a platform-specific implementation of GovCMS8 over at govcms/govcms8lagoon.
We set HSTS in seckit at https://github.com/govCMS/govcms8lagoon/blob/master/.docker/images/govcms8/settings/settings.php#L98-L102

For CSP, we currently allow agencies to set their own CSPs (again via SecKit) - we are working on making this easier for them to manage.
