### ISSUE TITLE
Password reset results in a crash

### ISSUE THREAD

**Issue by MikeGlew** [govCMS/govcms8-installer#301]
OOTB the GovCMS beta build results in a crash if I enter an email not associated with a user account into the password reset screen.  If I use an email that IS associated with a user account, the crash does not occur.  This constitutes a security concern...  Hackers can keep retrying email addresses until the crash does not occur to ensure they have a valid email.

The website encountered an unexpected error. Please try again later.
Error: Call to a member function id() on null in event_log_track_auth_form_submit() (line 51 of modules/contrib/events_log_track/event_log_track_auth/event_log_track_auth.module).
event_log_track_auth_form_submit(Array, Object, 'user_pass') (Line: 158)
event_log_track_form_submit(Array, Object)
call_user_func_array('event_log_track_form_submit', Array) (Line: 111)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 590)
Drupal\Core\Form\FormBuilder->processForm('user_pass', Array, Object) (Line: 319)
Drupal\Core\Form\FormBuilder->buildForm('user_pass', Object) (Line: 93)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 50)
Drupal\ban\BanMiddleware->handle(Object, 1, 1) (Line: 99)
Drupal\shield\ShieldMiddleware->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by tobybellwood** [comment]
Looks like this is already raised on d.o. - https://www.drupal.org/project/events_log_track/issues/3060838

**Comment by MikeGlew** [comment]
Seems to have been reviewed and tested - can you apply it to the GovCMS baseline?

**Comment by MikeGlew** [comment]
This doesn;t seem to be in the current baseline.  Can you please reopen this defect?
