### ISSUE TITLE
Large menu tree is not manageable in admin UI

### ISSUE THREAD

**Issue by mehmoodrehman** [govCMS/govcms8-installer#314]
We have a new website that has about 2000 menu items in single menu. Menu tree is displaying correctly but menu rearrange feature doesn't work. We have tried drag method as well as weight 
 input field (by updating menu item weight, swapped menu weight number to move a sub tree), changes are not saved.

I have noticed, tabledrag plugin is used and it appears browser cannot handle this many event handlers attached on single page. The page is slow as well as changes are not saved, even after 
apparent successful drag operation.

There might be a solution to hide/show sublevels by applying a custom admin theme with some changes to table__menu_overview twig, but it would not be ideal for long term. We will work on local development environment.

I have come across BigMenu module that claims to resolve this issue, there is only alpha release for Drupal 8. I will try to test this module locally and will share results here.

Can you please advise whether this module can be added to the approved GovCMS modules in SaaS after going through due process or there is an alternative solution to this problem?

Regards,
Mehmood

**Comment by brett-sargeant** [comment]
Is it possible to nest menus as a work around?

**Comment by mehmoodrehman** [comment]
There are 4 subsites and separate menus are already setup to reduce the depth. Currently this website has 22 menus (including system).

**Comment by brett-sargeant** [comment]
ouch. ok, That is going to be tricky.

edit: are you in the govcms slack channel?

**Comment by mehmoodrehman** [comment]
Not yet,

**Comment by brett-sargeant** [comment]
Sometimes you can get more responses there. Though I'm not sure that would be what happens in this case.

**Comment by pameeela** [comment]
Hi,

I would like to +1 the request to add Big Menu - we requested this in a support ticket a few months ago.

We have a site with ~700 menu links (and growing). The menu admin page breaks at 500.

Big menu solves this issue but also makes it so much easier to work with, even for menus under the 500 threshold.

**Comment by OPCIT** [comment]
Big Menu works great for managing large menu structures.

**Comment by mingsong-hu** [comment]
I would recommend my contributed module [Hierarchy Manager](https://www.drupal.org/project/hierarchy_manager)  which provides a plugin architecture to delivery a flexibility of managing hierarchy for taxonomy terms, menu links and others. 
Hierarchy Manager module provides following features:
- Support massive hierarchy tree (> 1000 nodes)
- Filtering
- In place editing
- Customize styling

**Comment by AlexSkrypnyk** [comment]
Here is a separate issue to include Bigmenu module https://github.com/govCMS/govCMS8/issues/409

**Comment by thisisalistairsaccount** [comment]
Hi everyone, as per [#409](https://github.com/govCMS/GovCMS8/issues/409) as part of our release this week, Big Menu has been included as part of the 1.10 release:

- released to GitHub on Mon 19 October 2020 - https://www.drupal.org/project/govcms8/releases/8.x-1.10
- deployed to SaaS sites Wed 21 October 2020
