### ISSUE TITLE
Add anchor_link module to govCMS 8

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/govcms8-installer#315]
The anchor_link module allows user friendly adding anchor in the rich-text editor.

The Drupal 7 Ckeditor includes this feature but Drupal 8 version doesn't.

https://www.drupal.org/project/anchor_link

**Comment by joshua-graham-adelphi** [comment]
Related to #316

**Comment by MikeGlew** [comment]
We really would like to see this anchor_link module added.

Mike Glew
NLA

**Comment by Corey-ATO** [comment]
At the ATO we have migrated a website to the GOVCMS platform - Drupal 8 and we are unable to create bookmarks as the CKEditor Anchor Link module is not installed. We do not want to manually manipulate html code to add anchors into content. Bookmarks are used to make the user experience better when engaging with our content. Please consider adding this module to the Drupal 8 GOVCMS platform.

**Comment by simesy** [comment]
This is only possible by content editors, editing `source` (urgh), so this would be a valuable addition, however could someone please use the new [request template](https://github.com/govCMS/govCMS8/issues/new?assignees=&labels=enhancement&template=module-request.md&title=Add+XXXX+module+to+GovCMS8) (or Joshua could you update this one).

**Comment by simesy** [comment]
Closing this in favour of #393
