### ISSUE TITLE
Add entity_usage module to GovCMS8

### ISSUE THREAD

**Issue by ivangrynenko** [govCMS/govcms8-installer#341]
** What value does this module/package add to GovCMS?
It allows identifying pages where a media entity is being used.
It allows avoiding running complex SQL queries.

** Please provide a brief outline of what this module does.
This module provides a tool to track entity relationships in Drupal.
Currently, the following tracking methods are supported:
- Entities related through entity_reference fields
- Entities related through link fields
- Standard HTML links inside text fields.
- Entities embedded into text fields using the Entity Embed module
- Entities embedded into text fields using the LinkIt module
- Entities related through block_field fields
- Entities related through entity_reference_revisions fields
- Entities related through dynamic_entity_reference fields

** Who does this module benefit:
[ ] end users
[x] content editors
[x] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

Maybe build a complex view to display the list of pages using this media entity.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.

This is admin-only module.

** What is the maintenance and support status of the module. Describe the issue queue activity.

All issues
37 open, 3 RTBC, 132 total
Bug report
12 open, 1 RTBC, 58 total

<img width="324" alt="image" src="https://user-images.githubusercontent.com/2966198/66888705-63321f80-f02b-11e9-942e-5dc03094ea41.png">

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?

`'access entity usage statistics'`

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

A new table `entity_usage` will be created.

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
This module is not intended for the public.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
The issues queue is a bit of a worry, but other than that it looks well maintainer and a quality piece of software.

** Additional information
Documentation of the module:
https://www.drupal.org/docs/8/modules/entity-usage/installation-and-basic-usage
https://git.drupalcode.org/project/entity_usage/blob/8.x-2.x/README.txt

**Comment by pameeela** [comment]
Just to be clear, building a view is not a viable alternative to this module, which provides complex entity tracking way beyond what you can do in views.

**Comment by Belhendo** [comment]
Hi Ivan and Pameeela

I've come on board as the new business-facing GovCMS product owner. Thank you for your input, this module does look interesting however we do require a certain level of public demand before adding modules.  We will keep this one on our radar. Belinda

**Comment by pameeela** [comment]
Hi Belinda,

Thank you for replying.

We are requesting this on behalf of our client, a small government agency, as it is proving to be a big problem for them not to be able to track usage.

Do you have any additional info on the public demand criteria, or how you are gauging public demand currently? That is pretty tricky in my opinion as a lot of these smaller agencies are not technical enough to know when a module might help them so they don't ask, or don't know how to ask. So it doesn't really seem like there is an effective way (currently) to get an accurate gauge of the actual public demand.

More than happy to discuss this further, beyond as it pertains to this specific request.

Cheers
Pam

**Comment by brett-sargeant** [comment]
I can see the value in it, particularly as we make extensive use of standard HTML links inside text fields in our existing sites that are being migrated.

**Comment by Belhendo** [comment]
Thanks Ivan, Pam and Brett for your contribution, we're currently discussing internally, I will be in touch again soon.

**Comment by Belhendo** [comment]
Hi Ivan, Pam and Brett, I'm going to set up a Zoom meeting for next week to discuss this with you all, Ru (one of the GovCMS senior developers) is investigating this in more detail and will be in the meeting to share his thoughts. Looking forward to meeting you all then!

**Comment by Belhendo** [comment]
Thanks for taking the time to workshop this module with us and using the new request template, we appreciate your time is valuable. We're hoping it won't require a call each time as we work to make the process more efficient. Adding modules to the distribution does increase our workload each time so we have to be careful.

We can see the use for this module for some sites, but I think from the meeting we all could acknowledge that the module is not as stable and supported as we'd like it to be, and the technical view is a lot of code complexity and potential for hard to track bugs. So we're not comfortable making it available for SaaS usage at this point, unless we saw much more demand for it above other modules we are considering.  Thanks again.
