### ISSUE TITLE
Can we replace Paranoia functionality with module_permissions?

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#38]
We utilise the [Paranoia ](https://www.drupal.org/project/paranoia) module in Drupal 7, but it can have undesirable side effects, usually as a result of overly zealous permission setting by module maintainers.

We can potentially replace the core of it's functionality with [module_permissions](https://www.drupal.org/project/module_permissions) - allowing the delegation of the ability control modules (and their permissions), whilst still maintaining a module/permission blacklist.

Any thoughts/comments?

**Comment by invisigoth** [comment]
It would probably be a better idea to specifically disable functions in a bespoke module as per ISM controls rather than relying on Paranoia.
 
One example of Paranoia being counterproductive is that we cannot grant site builders permissions to easily customise the display of file entity download links.

**Comment by simesy** [comment]
module_permissions looks good especially since it's by pandaskii

But isn't this covered by site audit?

**Comment by Belhendo** [comment]
Hi all

As you are already aware, Paranoia and Permissions are not part of D8 distribution.  Paranoia is still in alpha1 for D8 and no module exists for permissions so neither of these will be considered for D8 distro until there is a stable release.  At the moment some of this risk is mitigated by the site audits as site audits are now available for the D8 distro. I'm going to close this issue and we will revisit it when there are stable modules available. 

Thanks!
