### ISSUE TITLE
Add File Replace module to GovCMS8

### ISSUE THREAD

**Issue by macphersonj** [govCMS/govcms8-installer#382]
** What value does this module/package add to GovCMS?
Allows a file to be replace while keeping the URL in tact. 

We've got an extremely resource heavy site which sees organisations (Gov and non-Gov) as well as individuals either bookmarking or deep-linking to these resources. They are mostly PDFs. We have since discovered that replacing files adds a version number and and any absolute reference to them breaks. We currently have around 300 PDFs

** Please provide a brief outline of what this module does.
Allows a file to be replace while keeping the URL in tact. 

** Who does this module benefit:
[x] end users
[x] content editors
[ ] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
We could add all files to the filesystem, but this would make it impossible for content publishers to maintain their resources

** What is the maintenance and support status of the module. Describe the issue queue activity.
![Screen Shot 2019-11-21 at 12 08 42 pm](https://user-images.githubusercontent.com/8557315/69291637-f4fb0100-0c57-11ea-8a08-c2269d7a4c0a.png)

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
'Replace files'

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
Not sure

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
Yes

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
 Developers are keen to maintain it and the issues seem to be addressed.

** Additional information
Whilst not overly popular, it addresses what we've discovered to be a major flaw for our users.

https://www.drupal.org/project/file_replace

**Comment by brett-sargeant** [comment]
Agree

**Comment by simesy** [comment]
My personal assessment of this module is it's technically very simple and high value for gov.

**Comment by simesy** [comment]
```
** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

> Not sure
```
This is a "no". This module just replaces the files. The point of this question is "could it be disaster rolling back this module" - there would be no rollback issues with this module.

**Comment by simesy** [comment]
> ** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

I've not found a alternative solution for this in an existing saas site without disaster level theme hacking.

**Comment by Belhendo** [comment]
Hi everyone
We acknowledge how useful this module is and that the code within the module itself is very simple.
I've been provided advice however that it's possible to execute a shell command when uploading a file. We're interested in seeing this issue resolved so we can further investigate making this module available.

**Comment by simesy** [comment]
Issue created https://www.drupal.org/project/file_replace/issues/3098622

**Comment by klonos** [comment]
Just chiming in to say that we receive many requests in the GovCMS Service Desk re retaining filenames, and this issue always comes up during GovCMS trainings. So +1 for adding it.

Re the `file_replace_shell_exec` submodule, and the request to split it off to a separate project, I don't see how that can be a blocker. Being a separate submodule, it means that we can keep it disabled, and I see no dependency defined in the .info file of the main module for it.

**Comment by simesy** [comment]
OK great to know @klonos, I did work with a client who had this problem, and I was a bit surprised it wasn't a bigger problem.

The best outcome is if the module maintainer offers a solution on my issue above, because this would solve the problem upstream.

But if that doesn't work out, and we want to add the module, there are a heaps of ways to prevent this sub package being installed - perhaps the simplest would be a patch to remove it during the build, but there are plenty of ways.

**Comment by Belhendo** [comment]
Thanks for the request and ensuing conversation. We're going to move forward with our internal process of testing with a view to including this module in the distro. I'll keep you posted.

**Comment by Belhendo** [comment]
Closing this as it links to GovCMS8 #401.
