### ISSUE TITLE
Unable to upgrade drupal/core to 8.7.11 

### ISSUE THREAD

**Issue by ArjunKishore** [govCMS/govcms8-installer#390]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - govcms/govcms 1.0.0-beta11 requires drupal/core 8.7.9 -> satisfiable by drupal/core[8.7.9] but these conflict with your requirements or minimum-stability.
    - govcms/govcms 1.0.0-beta11 requires drupal/core 8.7.9 -> satisfiable by drupal/core[8.7.9] but these conflict with your requirements or minimum-stability.
    - govcms/govcms 1.0.0-beta11 requires drupal/core 8.7.9 -> satisfiable by drupal/core[8.7.9] but these conflict with your requirements or minimum-stability.
    - Installation request for govcms/govcms 1.0.0-beta11 -> satisfiable by govcms/govcms[1.0.0-beta11].

Installation failed, reverting ./composer.json to its original content.`

**Comment by blissjeffrey** [comment]
report here pls. [#386](https://github.com/govCMS/govCMS8/issues/386)

**Comment by monymirza** [comment]
Report here pls #386

**Comment by simesy** [comment]
drupal/core 8.7.11 conflicts with govcms/govcms beta11 because
https://github.com/govCMS/govCMS8/blob/1.x/composer.json#L42

**Comment by fubarhouse** [comment]
You can also use the branch we've got building for this:
```
https://github.com/govCMS/govCMS8/tree/release/1.0-stable
```

Use at your own discretion.
You can diff the branches to see what we did to upgrade the core version.
Note the changes to `composer.json`.
