### ISSUE TITLE
Update Webform module

### ISSUE THREAD

**Issue by mah-sanjay** [govCMS/govcms8-installer#396]
Hi,
I am trying to add captcha element to all the webforms. Trying to add the captcha element gave me some ajax error.

Going through the issue queue of webform module, i found out that this issue has been solved in later version of the webform module.
I checked available updates for the site and found that webform module is still in 8.5.1 version whereas the latest webform module is in 8.5.8 version.
Can we update webform module to latest version?
Thank you!

**Comment by Belhendo** [comment]
Hi @mah-sanjay, thanks for raising this issue. We will be updating to the latest version in our upcoming D8 release.

**Comment by Belhendo** [comment]
Update - this will be included in the upcoming GovCMS D8 distro release https://www.drupal.org/project/govcms8/releases/8.x-1.1, from 1800 on Wednesday 26/2/2020.
