### ISSUE TITLE
d8/9 default theme content type - publications

### ISSUE THREAD

**Issue by brett-sargeant** [govCMS/govcms8-installer#398]
Something to consider adding to the default theme when it's updated: A publications content type that will allow for a publications library, with a taxonomy for different categories.

**Comment by simesy** [comment]
Lack of a `publication` type is one of those oddities of govcms, to be sure. It's a pretty common pattern for government sites. I would like to see a bit of a refresh of the content model in the next version of the distribution, fwiw. I delete all the content types in any new build.

**Comment by brett-sargeant** [comment]
It would be good to have an updated theme with all the bugs ironed out prior to 9 being pushed out. Particularly if there ends up being a Finance SaaS 7 -> 9 project at some point.

**Comment by Belhendo** [comment]
Hi @brett-sargeant and @simesy 

Thanks for your input Brett and Si, we'll keep it in mind when we get to that stage. 

I'm going to close this ticket now, please raise another issue if you need to.
