### ISSUE TITLE
Add twig_tweak module to GovCMS8

### ISSUE THREAD

**Issue by simesy** [govCMS/govcms8-installer#399]
** Please provide a brief outline of what this module does.

"Twig" is a templating language (that in Drupal is converted to PHP), and allows a site builder to output HTML structures. This module adds a lot of useful "twig functions" for themers, for outputting complex things very easily.

** What value does this module/package add to GovCMS?

1. Strategically, govcms should enable SaaS sites to have reduced amounts PHP. This module significantly increases what can be done in twig templates. Twig templates have a well-defined audit surface compared to raw PHP. Some simple sites may be able to avoid PHP with this module.

2. Many site builders have strong "frontend" skills, but lack PHP skills. So there is a tendency to solve problems with twig (loops/variables) than in PHP. This module allows such twig solutions to be drastically simpler to implement and maintain.

3. There are simply some things that are hard to do in Drupal core twig. An example is printing a file/url path from a file entity on a media entity on a node entity. So this just makes stuff easier.

** Who does this module benefit:
[ ] end users
[ ] content editors
[x] site builders
[x] themers
[x] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

Every case is different, but essentially you're reducing the amount and complexity of PHP and Twig in your theme. There are a range of examples here
https://www.drupal.org/docs/8/modules/twig-tweak/cheat-sheet

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.

See above.

** What is the maintenance and support status of the module. Describe the issue queue activity.

I consider it stable and well supported. A look at the issue queue shows most bugs/issues in a closed state. After a rewrite from the 1.x version, the module has had four 2.x point releases (is stable). The module developer is a 10 year contibutor with 1000 commits across projects https://www.drupal.org/u/chi

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?

There are no API interactions other than extending the twig functions available, following standard permissions handling of any twig functionality.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

No

** Is the module designed to capture anonymous user data?

No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.

Yes

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?

Good quality. Great uptake - very popular. 2.x version.

<img width="960" alt="Screen Shot 2020-02-07 at 12 18 06 pm" src="https://user-images.githubusercontent.com/188856/73992719-0aa0dc80-49a4-11ea-8829-c1eabf2c65f0.png">

** Additional information

Has been request many times.

https://github.com/govCMS/govCMS8/issues/108#issuecomment-414601441
https://github.com/govCMS/govCMS8/issues/215

<img width="555" alt="Screen Shot 2020-02-07 at 12 28 32 pm" src="https://user-images.githubusercontent.com/188856/73993122-67e95d80-49a5-11ea-9b67-25a445535848.png">

**Comment by simesy** [comment]
Something to be mindful of is this module does a "check_access" false on entity views. This avoids caching issues but could potentially allow entities to be printed that would not otherwise be viewable. In theory a govcms site should have no such content, and this is not a new threat because someone could blindly put the same or worse php into a `.theme` file.

**Comment by Belhendo** [comment]
Thanks for raising this @simesy, this is currently under internal review.

**Comment by thisisalistairsaccount** [comment]
With the release of GovCMS Drupal 9, we've included Twig Tweak as part of the 9 distribution at https://github.com/govCMS/GovCMS

With the end of life of Drupal 8 later this year, the recommendation would be to upgrade or move to Drupal 9 to utilise Twig Tweak

**Comment by thisisalistairsaccount** [comment]
Should have been closed previous, noting added as part of Drupal 9 release
