### ISSUE TITLE
Apache Solr older than 6.4 are End Of Life (EOL)

### ISSUE THREAD

**Issue by pandaskii** [govCMS/govcms8-installer#4]
Search API Solr Search module has a 2.x branch for this

REF: 
http://lucene.apache.org/solr/community.html

https://www.drupal.org/project/search_api_solr

**Comment by tobybellwood** [comment]
Currently (Dec2017) Acquia Search is currently incompatible with 8.x-2.x versions of Search API Solr Search (https://docs.acquia.com/acquia-search/modules)

**Comment by pandaskii** [comment]
Yes, Acquia search is using an End of Life version Solr unfortunately

**Comment by govhosting** [comment]
Search infrastructure related.  Closing but can be reopened if required.
