### ISSUE TITLE
Add media_entity_file_replace module to GovCMS8

### ISSUE THREAD

**Issue by AlexSkrypnyk** [govCMS/govcms8-installer#401]
** What value does this module/package add to GovCMS?
Allows to replace files attached to media entities without the change of the file name.
https://www.drupal.org/project/media_entity_file_replace

Some clients require to regularly update previously uploaded files (PDFs, docs etc) with the new version without changing the file name.

** Please provide a brief outline of what this module does.
This module allows content editors to easily replace the source files associated with file-based media types (like "Document"). The replacement file overwrites the existing file, keeping the same filename and path, which is usually what content editors want to do when performing a file replacement.

This module operates on the media entity level, meaning the file replacement is done by accessing the edit form for a media entity that has a file source field on it. If you're using Drupal's media module for document management, then this is what you want.

Without this module, content editors would typically try and replace a file by editing the media entity, using the "remove" button on the file widget, and uploading a new replacement file with the same filename. However, this does not work as intended, as Drupal will append a number to the end of the replacement file, like `_1` or `_2`, instead of actually overwriting the original. The only workaround is to delete the media entity, hope the site is configured to automatically delete unused files on cron runs, wait for that deletion to occur, and then upload a new document with the same filename.

** Who does this module benefit:
[x] end users
[x] content editors
[ ] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
Not possible to implement on theme level as requires integration with media entity.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
Does not apply. This module works with files.

** What is the maintenance and support status of the module. Describe the issue queue activity.
Current module version is `8.x-1.0-beta2` with recent update done 3 weeks ago. The module is quite new. However, it was extensively tested on non-govcms projects.

Module has test coverage (Functional Drupal tests).

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
None, the module does not add any new permissions

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No, nothing is stored. All file manipulations happen during file upload.

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
Does not apply. Module code only runs during file upload by the content editor user.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
Current maintainer is https://www.drupal.org/u/bkosborne (9years 9 month on D.O.), has a long list of contributions.

** Additional information
N/A

**Comment by brett-sargeant** [comment]
Is this doing the same as https://github.com/govCMS/govCMS8/issues/382

**Comment by simesy** [comment]
Looks like it might be a better option. From  the project page:

> The File Replace module does something similar to this module, but it doesn't integrate with the Media module at all. Instead editors must access a special form for each individual file entity and perform the replacement upload there.

**Comment by brett-sargeant** [comment]
ok, this one does seem better.

**Comment by Belhendo** [comment]
Thanks for your request @AlexSkrypnyk ,

This has passed the internal review process and is awaiting internal approval. Pending that, it will be added to the backlog for inclusion in the distro. I'll update when I have more info.

**Comment by simesy** [comment]
I looked at the codebase and was pleased to see it is only one file of code and not a big file. Extremely well documented and well tested.

**Comment by Belhendo** [comment]
Great news - https://www.drupal.org/project/media_entity_file_replace will be added to the distro as part of the next GovCMS D8 release: https://www.drupal.org/project/govcms8/releases/8.x-1.1 - this Wednesday night, 26/2/2020 from 1800.
