### ISSUE TITLE
Add Mini site module to GovCMS8

### ISSUE THREAD

**Issue by AlexSkrypnyk** [govCMS/govcms8-installer#402]
** What value does this module/package add to GovCMS?
Allows to upload archives with static sites.
https://www.drupal.org/project/minisite

** Please provide a brief outline of what this module does.
Allows to upload and archive with a 'minisite' files and serve it from a
Drupal website, while maintaining the minisite's look and feel.

The pages can be served from the location in the public or private files
directory or from an alias set on the parent entity (where the field is attached
to).

** Who does this module benefit:
[x] end users
[x] content editors
[x] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
Not possible

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
Not possible to replicate with a theme.

** What is the maintenance and support status of the module. Describe the issue queue activity.
The module is quite new. Current version is `8.x-1.0-alpha6`. The `8.x` version of the module has just been developed recently, so there are not many sites using it.
The module is actively maintained.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
The same permissions as uploading files.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
This module creates it's own table to store special redirects. It does not modify the database structure, apart from providing a new field type (so the modifications are the same as any field storage and configuration). It does not modify other fields.

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
The module provides a field formatter that is cacheable. The output of the field formatter is a link to the static site, hosted within the Drupal's public files. So neither the page that renders the formatter nor static site page are breaking cache.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?

Current module maintainer is Alex Skrypnyk (me) https://www.drupal.org/u/alexskrypnyk
On Drupal.org for 10 years 3 months.

Module has significant unit and functional test coverage.
Any changes going through CI process (CircleCI).
Code adheres to Drupal standards.

** Additional information
None

**Comment by simesy** [comment]
+1 Takes a lot of pressure off drupal itself, where single-use content types might be set up to serve awkward microsites from nodes.

A workaround is to just commit static files to the repo (and in theory add a custom lagoon route for clean paths). That takes Drupal out of the equation altogether. I did this with one project as a workaround while waiting for microsite to land.

**Comment by brett-sargeant** [comment]
+1, however I thought this was on a list that was being progressed for addition already?

**Comment by simesy** [comment]
@brett-sargeant correct but generally we've been trying to have a public record for every module request. Aside from transparency it also provides a public forum for discussing alternative approaches.

**Comment by simesy** [comment]
I have a question for govcms team - does saas allow custom routes (aka custom domains names) that can point to the mini-site?  @ruwanl

**Comment by Belhendo** [comment]
Hi all

GovCMS CAB has approved the addition of this module to the D8 distro when there is a stable version.

**Comment by thisisalistairsaccount** [comment]
Hi All,

Mini site 1.3 was added to the GovCMS 8 distro as part of https://www.drupal.org/project/govcms8/releases/8.x-1.4 on 5 June 2020.
