### ISSUE TITLE
Add bigmenu module to GovCMS8

### ISSUE THREAD

**Issue by stooit** [govCMS/govcms8-installer#409]
Request to add [bigmenu](https://www.drupal.org/project/bigmenu) to the Drupal 8 distribution.

** What value does this module/package add to GovCMS?

Large sites can have large menu structures which can make content entry difficult (or sometimes impossible).

When sites have very large menu structures (e.g thousands of items) the Menu administrative interface can fail due to:
- Initial menu structure page does not load (timeout)
- Inability to actually use (UX - cannot reasonably drag a menu item to new parent due to page size)

** Please provide a brief outline of what this module does.

This module renders Menu administration page with collapsed sub-trees (configurable depth), and retrieves menu results via AJAX. This resolves two issues:
  - UX in maintaining menus
  - Scale issues (large menus will cause timeouts/errors as PHP takes too long to render the page)

** Who does this module benefit:
[ ] end users
[X] content editors
[ ] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

Not practical to resolve in the theme layer

This module replaces the standard Menu Form (administrative inferface). It is not possible to override the class responsible outside of a module.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.

As above

** What is the maintenance and support status of the module. Describe the issue queue activity.

Actively maintained, D8 version has an alpha release available which has been tested with success within the GovCMS distribution.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?

No additional permissions required/available. Available once module is enabled.

Provides a configurable override for depth (but not exposed via a UI) and not likely to ever need overriding from default (1).

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

No

** Is the module designed to capture anonymous user data?

No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.

Not relevant (no public-facing content render)

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?

The code is lightweight and clearly documented. Automated tests exist.

The module has 5600 sites currently using it, and no major issues exist in the issue or bug lists.

Response rate is 100%, with first response at 33h.

**Comment by mingsong-hu** [comment]
I am wondering if the 2.0.0-rc1 version is covered by Drupal security advisory policy?

The shield icon is not showing with that version.

**Comment by thisisalistairsaccount** [comment]
Bigmenu module has been added to GovCMS8 at 2.0.0-rc1:

- released to GitHub on Mon 19 October 2020 - https://www.drupal.org/project/govcms8/releases/8.x-1.10
- deployed to SaaS sites Wed 21 October 2020
