### ISSUE TITLE
Add IP Login module to GovCMS8

### ISSUE THREAD

**Issue by gracechanggao94** [govCMS/govcms8-installer#416]
** What value does this module/package add to GovCMS?
The ip login module provides an alternative method for users to log in the website.

** Please provide a brief outline of what this module does.
This module allows users to login first automatically via their IP address, wildcard or range, instead of using a username / password. The module uses the core 'Profile' module to lookup a user's IP address

** Who does this module benefit:
[x] end users
[x] content editors
[x] site builders
[x] themers
[x] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
No alternative methods.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
As above

** What is the maintenance and support status of the module. Describe the issue queue activity.
Not quite active.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
The iplogin.routing.yml routes need the permission check added.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
Not relevant

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
The code is pretty clear and simple. 

** Additional information
https://git.drupalcode.org/project/ip_login

**Comment by Belhendo** [comment]
Hi Grace 

Thank you for your interest in adding modules to the GovCMS distribution. 

In line with the Australian Government Information Security Manual, the GovCMS policy is that access must be authenticated by a user name and a password. Also, most agencies have a public IP address that doesn't differentiate between users. Based on these considerations, we will not be progressing further in investigating this module for inclusion in the GovCMS distirbution.
