### ISSUE TITLE
Add IP address fields module to GovCMS8

### ISSUE THREAD

**Issue by gracechanggao94** [govCMS/govcms8-installer#417]
** What value does this module/package add to GovCMS?
There is no default filed to store the IP address or range.

** Please provide a brief outline of what this module does.
This module provides a field for storing an IP address or range.

** Who does this module benefit:
[x] end users
[x] content editors
[x] site builders
[x] themers
[x] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
Not possible.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
As above.

** What is the maintenance and support status of the module. Describe the issue queue activity.
The last change happened 10 months ago.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
No.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No.

** Is the module designed to capture anonymous user data?
No.

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
Not relevant.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
The code is clear with test cases.

** Additional information
https://github.com/bjaxelsen/field_ipaddress

**Comment by Belhendo** [comment]
Hi @gracechanggao94 

Thank you for your request. Unfortunately this is not a drupal supported module, so we will not be able to consider adding it to the distribution.
