### ISSUE TITLE
Monitoring storage, upload file size and private directory actions

### ISSUE THREAD

**Issue by gigimaor** [govCMS/govcms8-installer#430]
I work for QFCC.
We using the service GovCMS PaaS to host the main website https://www.qfcc.qld.gov.au.

Since we using webforms files upload fields to give our user the option to send us large files, the files uploaded to the private directory may be overloaded with the storage quota. 
The current upload size limit is 256Mb but some of the required files maybe 700Mb.

The files should be temporarily available to the manager and he needs the option to delete them after download it to its local machine.

Solution required
1. We would like to have on GovCMS dashboard the option to monitor the storage quota.
2. We would like to have the option to delete/remove old/unused files from the private directory. 
2.1 as a task
2.2 as a cronjob
2.3 individual by an online file manager
3. We would like to have the options to control the upload file allow size.

**Comment by tobybellwood** [comment]
Hi @gigimaor - as a PaaS customer, you have much more flexibility to add contrib/custom modules or modify configuration.

You can configure a cronjob in the .lagoon.yml file (https://lagoon.readthedocs.io/en/latest/using_lagoon/lagoon_yml/#cron-jobs-environmentsnamecronjobs)

Tasks are defined as lagoon-wide, so wouldn't be a suitable vehicle for this, but you could look at third party Drupal modules that permit this function (IIRC there are a couple for D8).

You can also modify any settings.php settings needed to control file upload size.  Note that larger files will not be automatically scanned for viruses, so you will need to consider the risk appropriately.

As for storage consumed - we're working on that.  Recent releases of Lagoon have improved some of those metrics - we just need to work out how to surface them.

**Comment by Belhendo** [comment]
HI @gigimaor 

Thanks for your interest, Toby has addressed your questions specifically above but for note in future, the issues tab here in Github is for requests for changes to the SaaS distribution. If you have ideas or requests for changes to the infrastructure, please communicate these to us by raising a service desk ticket. Thank you!
