### ISSUE TITLE
Add recyclebin/trash module to GovCMS8

### ISSUE THREAD

**Issue by StevenKotevski** [govCMS/govcms8-installer#436]
** What value does this module/package add to GovCMS?

** Please provide a brief outline of what this module does.
Trash:
This module adds a trash bin for nodes. Nodes can be moved to the trash instead of being deleted and thus can be restored or permanently deleted later on.

recyclebin:
 a recycle bin for nodes. When a node is deleted it goes into the "recycle bin", meaning that it is deleted from drupal but stored in some separate database tables. Data retained includes the node, accompanying revisions and comments. The module will include a UI for browsing deleted nodes and restoring them.

** Who does this module benefit:
[ ] end users
[ X] content editors
[ X] site builders
[ ] themers
[ X] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.

** What is the maintenance and support status of the module. Describe the issue queue activity.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?

** Is the module designed to capture anonymous user data?

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?

** Additional information

**Comment by StevenKotevski** [comment]
Links to modules:
https://www.drupal.org/project/recyclebin
https://www.drupal.org/project/trash

**Comment by StevenKotevski** [comment]
Please feel free to copy a question from above and answer it with a new comment. I will then edit my initial response with the answers.

**Comment by simesy** [comment]
recyclebin module does not have any code.

The 'trash` functionality is already doable in my opinion, especially since in government my preference is to never delete content anyway. You can have an "Archive" workflow state (call it "Trashed") if you like. This state should unpublish the node. Later an admin can "empty the trash" by deleting all "Archived" content.

**Comment by thisisalistairsaccount** [comment]
> The 'trash` functionality is already doable in my opinion, especially since in government my preference is to never delete content anyway. You can have an "Archive" workflow state (call it "Trashed") if you like. This state should unpublish the node. Later an admin can "empty the trash" by deleting all "Archived" content.

Agreed. I think this can be achieved from a content design perspective and thinking about workflow/process in a site already without needing further modules to achieve this.

**Comment by brett-sargeant** [comment]
Nodes can already use the archive status out of the box, however neither that, nor from what I can see the two modules above will work on files. How will they be handled when linked from an archive page and required not to be available publicly?

There is regularly a need to remove content of all types from the sites - particularly if a file contains details that were accidentally published. 

IIRC GvCMS isn't considered a records management system, so records need to be maintained separately on what has been published/approved etc. for the required time frame, which is likely where the never delete perception comes in.
