### ISSUE TITLE
Diagnostic-Code: smtp;554 Transaction failed: Duplicate header 'From'.

### ISSUE THREAD

**Issue by mike-speedwell** [govCMS/govcms8-installer#437]
Getting error when sending mail on IIS connecting to Amazon SES. Looking into the headers, it looks like this is the part where it's doubling. And it seems to be the Contact Module causing this or not sure. Anyone experienced this? 

from: sender name <no-reply@bl------.com.au>
From: no-reply@bl-------.com.au

**Comment by tobybellwood** [comment]
Hi @mike-speedwell  - if you've got access to the servicedesk, please raise a ticket, and we can look into this.  Is this D7 or D8?

**Comment by mike-speedwell** [comment]
Hi Toby, thanks for the response...this is D8. Checking if we have servicedesk.

--
Best regards,
Michael Montero


Kind Regards
Michael Montero
PHP Developer

E m.montero@speedwell.com.au<mailto:m.montero@speedwell.com.au> | D     | W www.speedwell.com.au<http://www.speedwell.com.au>

<http://>
[Partner with us. Accelerate your goals with our expertise. View our customer success stories.]<https://speedwell.com.au/?utm_source=Email-Footer&utm_medium=Email-Footer&utm_campaign=Jan2020>
BRISBANE | 07 3891 2299
SYDNEY | 02 8006 0000
CANBERRA | 02 6100 3444
MELBOURNE | 03 9016 0000
AUSTRALIA-WIDE | 1300 077 333 (13 000 SPEED)    Speedwell Pty Ltd
ABN 37 110 700 920
Speedwell House
105 Brunswick Street | PO Box 1057
Fortitude Valley QLD 4006



STANDARD TERMS & CONDITIONS
Unless otherwise agreed in writing, all services provided by Speedwell are supplied under our Standard Terms and Conditions<https://speedwell.com.au/about-us/terms-and-conditions>

IMPORTANT NOTICE REGARDING CONFIDENTIALITY
This electronic mail message is intended only for the addressee and may contain confidential information. If you are not the addressee, you are notified that any transmission, distribution or photocopying of this -mail is strictly prohibited. The confidentiality attached to this e-mail is not waived, lost or destroyed by reasons of a mistaken delivery to you. If you have received this email in error please notify the sender of this message.


________________________________

**Comment by Belhendo** [comment]
I'm going to close this ticket now. Thanks all!
