### ISSUE TITLE
Add GovCMS Alert module to GovCMS8.

### ISSUE THREAD

**Issue by sonnykt** [govCMS/govcms8-installer#452]
** What value does this module/package add to GovCMS?
This module provides a site-wide alert message and announcement.

** Please provide a brief outline of what this module does.
The module provides content-managed alert messages which will be displayed on top of every page on front-end.

** Who does this module benefit:
[x] end users
[ ] content editors
[x] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
This module is introduced as part of GovCMS so that all available GovCMS sites do not need to build the alert functionality themselves.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
Yes, the theme can override the JS and CSS provided by the module.

** What is the maintenance and support status of the module. Describe the issue queue activity.
None - this module is introduced as part of GovCMS.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
Standard node related permissions to manage the Alert content type as well as new permission `administer govcms_alert` to toggle the site-wide alert block. All relevant permissions are granted to the `site_administrator` role upon installation.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No - the module adds a new content type Alert (`govcms_alert`).

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
Yes - the module adds a `<div>` tag to the `page_top` region. Its JS will load the active alerts via Ajax calls and injects into the pages so that the alerts do not impact any page cache. Publishing an alert does not require to purge CDN cache.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
This module is introduced as part of GovCMS.

** Additional information
Pull Request: https://github.com/govCMS/govCMS8/pull/451

**Comment by pellegs** [comment]
Is this an existing Drupal contrib module or a custom module developed by Salsa?

**Comment by sonnykt** [comment]
@pellegs It's a custom module developed by Salsa as per requests from some gov agencies. Functional-wide it's similar to the sitewide_alert module, however, it's more customisable.
You can see the Pull Request in https://github.com/govCMS/govCMS8/pull/451

**Comment by pellegs** [comment]
Hi @sonnykt, The module would need to be submitted to Drupal.org as a contrib module.  I also think it should be renamed to something more generic and not just specific for govCMS.  What other contrib modules do something similar to this?
