### ISSUE TITLE
syntax error upon installation of GovCMS8

### ISSUE THREAD

**Issue by schnydszch** [govCMS/govcms8-installer#459]
Hi! I'm trying out govCMS8 and I am getting the following error upon installation of Drupal govCMS8.
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?rewrite=ok&profile=govcms&langcode=en&id=1&op=do_nojs&op=do
StatusText: OK
ResponseText: ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in Composer\Autoload\includeFile() (line 61 of /var/www/MY_PROJECT/docroot/modules/contrib/scheduled_transitions/src/Entity/ScheduledTransition.php).

ResponseText: ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in Composer\Autoload\includeFile() (line 61 of /var/www/MY_PROJECT/docroot/modules/contrib/scheduled_transitions/src/Entity/ScheduledTransition.php).

My environment is Ubuntu 16.04.6 LTS, Php 7.3.18, Apache2,  Drush 9.7.2., MariaDB 10.0.38.
I was able to successfully install to an Ubuntu 18.x environment.
Thanks in advance!

**Comment by pandaskii** [comment]
Such error only happens if the PHP version is < 7.1

Use a phpinfo() in a web page to check that since the cli and web may be running different PHP versions.

**Comment by schnydszch** [comment]
Hi! I can confirm that indeed the problem was due to PHP version is < 7.1. I checked the phpinfo() indeed cli is 7.3 and web is 7.0. Thank you very much!
