### ISSUE TITLE
Layout builder incompatibility with display suite module

### ISSUE THREAD

**Issue by Benjen** [govCMS/govcms8-installer#497]
There is a bug in the Display Suite module which causes a fatal error when one tries to enable layout builder on a display mode for a given content type. To work around this issue one can disable the Display Suite module; however, this particular bug has been fixed in the latest stable release of Display Suite (see [issue](https://www.drupal.org/project/ds/issues/3054607)).  GovCMS8 1.6.1 uses Display Suite 8.x-3.2. Updating Display Suite 8.x-3.8 fixes this issue.

**Comment by thisisalistairsaccount** [comment]
THanks @Benjen we'll take a look at the error and the stable release

**Comment by thisisalistairsaccount** [comment]
Display Suite module has been updated to 3.9:

- released to GitHub on Mon 19 October 2020 - https://www.drupal.org/project/govcms8/releases/8.x-1.10
- deployed to SaaS sites Wed 21 October 2020
