### ISSUE TITLE
Update the environment_indicator module to 4.0.0

### ISSUE THREAD

**Issue by klonos** [govCMS/govcms8-installer#507]
The current [Environment Indicator](https://www.drupal.org/project/environment_indicator) module version in GovCSM8 is 3.5: https://github.com/govCMS/GovCMS8/blob/1.x/composer.json#L56

There is a known issue that throws this error:

```
in_array() expects parameter 2 to be array, null given in
/environment_indicator/environment_indicator.module on line 314
```

This was recently fixed in https://www.drupal.org/project/environment_indicator/issues/3020895, with https://www.drupal.org/files/issues/2020-02-04/3020895-environment-inarray-null-5.patch and the fix is included in the 4.0.0 version that was released in June 23, 2020.

We should update as soon as possible.

**Comment by thisisalistairsaccount** [comment]
Environment Indicator module has been updated to 4.0.0:

- released to GitHub on Mon 19 October 2020 - https://www.drupal.org/project/govcms8/releases/8.x-1.10 
- deployed to SaaS sites Wed 21 October 2020
