### ISSUE TITLE
Bug in Linked Field module breaks use of fields in Layout Builder

### ISSUE THREAD

**Issue by Benjen** [govCMS/govcms8-installer#511]
There is a [bug](https://www.drupal.org/project/linked_field/issues/2987464) in the [Linked Field](https://www.drupal.org/project/linked_field) module which prevents one from using Layout Builder to control the layout of fields in nodes and paragraphs. 

**To replicate:** 
Enable the Linked Field module and then try to add content fields to a layout container in Layout Builder for either nodes or paragraphs. When clicking the add field button the field is not added to the layout page and an error is throw which is captured in the Drupal error logs: 

![Screen Shot 2020-09-07 at 4 43 19 pm](https://user-images.githubusercontent.com/1292616/92356370-5594f500-f129-11ea-99a8-16d470d0782a.png)

This bug makes Layout Builder unusable for content layout.

**Work around:**
Don't use Linked Field module

**Solution:**
Upgrade Linked Field module 8.x-1.1 => 8.x-1.3 which fixes this issue.

**Comment by thisisalistairsaccount** [comment]
Linked Field module has been updated to 8.x-1.3:

- released to GitHub on Mon 19 October 2020 - https://www.drupal.org/project/govcms8/releases/8.x-1.10
- deployed to SaaS sites Wed 21 October 2020
