### ISSUE TITLE
Any release for the Drupal 8.8.10 or 8.9.6 which has recently got the security update?

### ISSUE THREAD

**Issue by Prekshapatel** [govCMS/govcms8-installer#514]
Hi there,

Could you please provide me the link for the release for  Drupal 8.8.10 or 8.9.6 which has recently got the security update or any plan to update it?

Thanks!

**Comment by thisisalistairsaccount** [comment]
Hi @Prekshapatel we had a release on the 24th of September - https://status.govcms.support/incidents/lzqz0g7jlbxh which moved us to 8.9.6
