### ISSUE TITLE
Allow theme implements hook_field_widget_multivalue_form_alter 

### ISSUE THREAD

**Issue by tannguyen04** [govCMS/govcms8-installer#538]
Hi
We already allowed theme implement `hook_field_widget_form_alter`.
Can we allow theme implements `hook_field_widget_multivalue_form_alter` too ?
For some case, admin theme need to alter field widget multiple value form to improve editor experience.

I have create a patch https://patch-diff.githubusercontent.com/raw/govCMS/GovCMS8/pull/539.patch

Thank you.

**Comment by joshua-graham-adelphi** [comment]
Second this - good for theming multivalued paragraphs in forms.

**Comment by joshua-graham-adelphi** [comment]
#539 - Linking the pull request.

**Comment by pandaskii** [comment]
@joshua-graham-adelphi Good point, the same requests could be happened to GovCMS 2.x (D9) as well

I will make sure at least `hook_field_widget_form_alter` being ported

**Comment by joshua-graham-adelphi** [comment]
Thanks.

I note that the function is Deprecated in Drupal 9.2.x - and should use  hook_field_widget_single_element_form_alter() instead. 

@see https://api.drupal.org/api/drupal/core%21modules%21field%21field.api.php/function/hook_field_widget_form_alter/9.2.x

**Comment by pandaskii** [comment]
Well noted thanks @joshua-graham-adelphi :)

**Comment by tannguyen04** [comment]
Thanks @joshua-graham-adelphi for you information.

**Comment by joshua-graham-adelphi** [comment]
hi @tannguyen04 - any plan to implement this?
