### ISSUE TITLE
Add Sitewide Alert module to GovCMS8

### ISSUE THREAD

**Issue by sonnykt** [govCMS/govcms8-installer#573]
** What value does this module/package add to GovCMS?
This module provides the site-wide alert messages.

** Please provide a brief outline of what this module does.
* Alerts are rendered at the top of the site regardless of the theme used (no block configuration).
* Multiple alerts can be displayed at once.
* Alerts can have different styles. The number and type of styles are configurable.
* Alerts can be (optionally) dismissed by visitors, so they are not notified again. 
* Alerts can be displayed on all pages (including administrative pages) or can be limited to a subset of pages.
* Alerts are loaded and displayed using a React component that will display new alerts immediately, even if a visitor is already on the page.
* Alerts were designed to avoid breaking your full page and dynamic caches.
* Alerts can be scheduled to show and hide at specific times.

** Who does this module benefit:
[ x ] end users
[ ] content editors
[ x ] site builders
[ ] themers
[ ] developers
 
** How could you provide/replicate the functionality of this module using alternative methods, eg in your theme?
Needs to use a content type (with taxonomy) for alerts, a Rest view to provide the alert messages via an API endpoint, and theme javascript to load the active alerts.

** If this module styles or alters HTML or JavaScript output, can the functionality be provided via the theme? What alternatives have you considered.
No -  requires a content type.

** What is the maintenance and support status of the module. Describe the issue queue activity.
Active development - Issue queue 13 open, 38 total.

** What permissions are needed to utilise the module (and are any new permissions provided by the module)?
The module defines a set of permissions from CRUD to administer the alert message. Usually only Site Admin and Site Builder should have those permissions.

** Does the module modify the database structure and/or store additional metadata on nodes or other entities? If so, why? What are the risks for future updates?
No - the module provides its own entity type.

** Is the module designed to capture anonymous user data?
No

** Is the output of the module typically fully cacheable? Would the inclusion of this module potentially render pages uncacheable.
Yes - all alerts are loaded via Ajax requests. The alerts do not impact page cache nor CDN cached pages.

** What is your assessment of the quality of this module, the contribution history of the module's maintainers, and the uptake of the module within the Drupal community?
The module is covered by Drupal Security Team.

** Additional information
https://www.drupal.org/project/sitewide_alert

**Comment by thisisalistairsaccount** [comment]
Hi @sonnykt I don't think we will add this one to the distribution. I think for the most part as it can be done with templating, views and controlled content types that there is little value in including this.

Considering most have gone down this route on their sites in 2020 with notifications in relation to Covid-19 and others with similar but different needs, that the ship has probably sailed on this one.
