### ISSUE TITLE
Drupal 8.9.10 compatibility

### ISSUE THREAD

**Issue by sas-sarkisian** [govCMS/govcms8-installer#574]
Hi,

Just wondering if there is a timeline on updating the govcms package to be compatible with Drupal 8.9.10?

There's been a recent security vulnerability patched in that release, and we're unable to update one of our sites to this version due to the govms package being incompatible. 

Thanks!

**Comment by thisisalistairsaccount** [comment]
GovCMS was updated to 8.9.11 on 15 Dec 2020: https://github.com/govCMS/GovCMS8/releases/tag/1.13.0
