### ISSUE TITLE
Composer install throws error drupal-composer/drupal-scaffold[2.4.0, ..., 2.6.1] require composer-plugin-api

### ISSUE THREAD

**Issue by schnydszch** [govCMS/govcms8-installer#586]
Hi all! I'm using composer 2 and upon installation composer install, I am receiving the following error:
Problem 1
    - drupal-composer/drupal-scaffold[2.4.0, ..., 2.6.1] require composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires drupal-composer/drupal-scaffold ^2.4 -> satisfiable by drupal-composer/drupal-scaffold[2.4.0, ..., 2.6

How do I go about this error? Thanks in advance!

**Comment by pandaskii** [comment]
GovCMS8 is not compatible with composer 2.x

You will have to revert the composer to 1.x :)

**Comment by tobybellwood** [comment]
removing the dependence on composer/drupal-scaffold (as per https://github.com/govCMS/GovCMS8/pull/478) should remediate this too.

**Comment by schnydszch** [comment]
Thanks for the info. I already tried using composer 1.9 instead of 2. Installation was okay. I will try tobybellwood's recommendation. Thanks and cheers!
