### ISSUE TITLE
Composer Update fails on phpunit/phpunit:6.5.3

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#6]
Testing with dependencies.io, it seems that our current composer configuration is un-upgradeable for phpunit (replicated in own environment).

It seems phpunit/phpunit:6.5.3 gets hung up on our phpunit/php-code-coverage:2.2.4 - which by rights is only depended by phpunit/phpunit.

A composer remove and require of phpunit/phpunit works fine and installs latest...

Not a current issue necessarily, but one to watch for?

```
Exec: cd /repo/ && composer require --dev --ignore-platform-reqs --no-scripts phpunit/phpunit:6.5.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit 6.5.3 -> satisfiable by phpunit/phpunit[6.5.3].
    - Conclusion: remove phpunit/php-code-coverage 2.2.4
    - Conclusion: don't install phpunit/php-code-coverage 2.2.4
    - phpunit/phpunit 6.5.3 requires phpunit/php-code-coverage ^5.3 -> satisfiable by phpunit/php-code-coverage[5.3.0, 5.3.x-dev].
    - Can only install one of: phpunit/php-code-coverage[5.3.0, 2.2.4].
    - Can only install one of: phpunit/php-code-coverage[5.3.x-dev, 2.2.4].
    - Installation request for phpunit/php-code-coverage (locked at 2.2.4) -> satisfiable by phpunit/php-code-coverage[2.2.4].
```

Of course, our current version 4.8.36 doesn't support php7.1 which may be the root of the issue (https://phpunit.de/)

**Comment by pandaskii** [comment]
It sounds like a different issue.

The requirement of PHPUnit is following the Drupal Core so we can keep the same testing behaviors

```"phpunit/phpunit": ">=4.8.35 <5"```

Ref: http://cgit.drupalcode.org/drupal/tree/core/composer.json?h=8.4.x

**Comment by pandaskii** [comment]
Ref: https://www.drupal.org/project/drupal/issues/2927806

Use PHPUnit 6 for testing when PHP version >= 7.2

Unlikely the Drupal core will bump the PHPUnit very soon

**Comment by tobybellwood** [comment]
Looks like there's some movement on this, alongside the proposal to drop php5 support...
 https://www.drupal.org/project/drupal/issues/2932606
