### ISSUE TITLE
Update cTools module to the security version 3.6

### ISSUE THREAD

**Issue by adrianopulz** [govCMS/govcms8-installer#619]
The cTools module is fixed on version 3.4 and has security issues. Version 3.6 release on 2021-May-13 resolves SA-CONTRIB-2021-009.

https://www.drupal.org/project/ctools/releases/8.x-3.6

**Comment by adrianopulz** [comment]
PR created: https://github.com/govCMS/GovCMS8/pull/621

**Comment by thisisalistairsaccount** [comment]
This was updated yesterday as part of This has been updated as part of the GovCMS release yesterday https://github.com/govCMS/GovCMS/releases/tag/1.17.0 - ctools was updated from 3.4 to 3.7
