### ISSUE TITLE
Media release content type should have published datetime field

### ISSUE THREAD

**Issue by ajbar7** [govCMS/govcms8-installer#62]
This should be separate from authored on field.

**Comment by enzolutions** [comment]
Hi @tobybellwood  && @ajbar7 

I just cloned 1.x branch and did a basic installation, but there are not content types, I choose a wrong branch? or how I could import all content type to try to contribute with this issue.

Thanks in advance

<img width="524" alt="govcms8-no-content-types" src="https://user-images.githubusercontent.com/907914/42957390-222c737c-8bb5-11e8-857d-8b16112ff8b6.png">

**Comment by tobybellwood** [comment]
Thanks @enzolutions - the content types are currently provided by an optional custom module (https://github.com/govCMS/govCMS8/tree/1.x/modules/custom/optional) - although this has undertaken some work as part of the base theme project, and we may well decide on making them non-optional (base theme dependency resolution reasons mostly, as well as some standardisation across installs)

The most recent branch is the https://github.com/govCMS/govCMS8/tree/g8bt-merge one

I'm going to put some time into creating a proper backlog (probs over the weekend) to give a better idea of where we're at!

**Comment by enzolutions** [comment]
Hi Toby.

Thanks for the response, I guess you are talking about **News and Media** custom/optional/govcms_optional_govcms_news_and_media module.

I will wait then your effort to merge the g8bt-merge branch and tidy the backlog.

At least is running in my machine :P

**Comment by enzolutions** [comment]
@tobybellwood Do you think this issue is still valid to work on it?

**Comment by tobybellwood** [comment]
I still think it's a valid addition - now we made the content types non-optional (to fix workflows) - it's at https://github.com/govCMS/govCMS8/tree/1.x/modules/custom/core/govcms_content_types/govcms_news_and_media

**Comment by simesy** [comment]
Fixed
