### ISSUE TITLE
Drupal Core security update 8.9.14 to 8.9.16

### ISSUE THREAD

**Issue by adrianopulz** [govCMS/govcms8-installer#620]
Resolves the issue: [Drupal core - Moderately critical - Cross Site Scripting - SA-CORE-2021-003](https://www.drupal.org/sa-core-2021-003)

https://www.drupal.org/project/drupal/releases/8.9.16

**Comment by adrianopulz** [comment]
PR created: https://github.com/govCMS/GovCMS8/pull/622

**Comment by thisisalistairsaccount** [comment]
Security update added as part of release yesterday - This has been updated as part of the GovCMS release yesterday https://github.com/govCMS/GovCMS/releases/tag/1.17.0 - 8.9.14 to 8.9.16
