### ISSUE TITLE
pdf module (https://www.drupal.org/project/pdf) - screen size is small

### ISSUE THREAD

**Issue by schnydszch** [govCMS/govcms8-installer#624]
Hi! I installed pdf module (https://www.drupal.org/project/pdf), using pdf.js viewer, the screen size is always small (Screenshot here: https://issuances-library.senate.gov.ph/sites/default/files/2021-10/Screenshot_1.png). Any hints on what to troubleshoot? Thanks!

**Comment by thisisalistairsaccount** [comment]
Hi @schnydszch this seems to relate to either the module's settings or CSS of the container that's rendering the PDF in the page.

This isn't part of our distribution so I don't think we can provide any further information than that. 

To note, our Drupal 8 distribution is end of life in line with Drupal 8 Core come 2 November 2021.
