### ISSUE TITLE
Profile Config vs Features

### ISSUE THREAD

**Issue by murraywoodman** [govCMS/govcms8-installer#65]
Mike Potter, the author of Features, has been telling people for a while not to use the Features module, suggesting that things would be easier and cleaner if normal config is used. There reasons for this are:

- there are usually interdependencies between features, make it hard to separate them.
- there are often namespace issues with field names etc.
- the dependencies are hard to calculate for the Features module.

It seems that there is a general desire to keep things simple and roll with config alone.

The only time Features should be used, it is suggested, is for distros where config is to be shipped and updated. In these cases the Features can be used to update the config. However, in GovCMS it is unlikely that Features would be used in this way. It is the general pattern that config is altered to suit the needs of the site. It would be unusual for features to be reverted in a GovCMS7 site. The same will probably hold true for GovCMS8.

Given the above, it is recommended that the Features module not be used to ship config. The suggestion is to do away with the current Feature modules based around content types and to ship them as Config contained in the install profile. They would be imported once at install time and then can be edited (and exported) by site builders as required.

This approach would free up the config significantly. At the moment there is a very rigid encapsulation for the content types, with shared fields being modelled separately. Relaxing this constraint would result in config which could be more richly interconnected:
- sharing of fields (where appropriate)
- sharing of paragraph bundles.

This may reduce the administrative burden on the GovCMS team as they are basically commiting to installing the best set of config they can at the time. The removal of Features would mean one less commitment to maintain going forward. ie. It removes the expectation that the Features config is something which is set in stone, allowing the distro to evolve over time.

I am wondering what the GovCMS team think of this approach as well as members of the wider community.

**Comment by tobybellwood** [comment]
Tracking the conversation over at https://www.drupal.org/project/ideas/issues/2957423 - it seems like it's gaining some traction

**Comment by simesy** [comment]
I think this is settled.
