### ISSUE TITLE
Known issues with PHP 7.2

### ISSUE THREAD

**Issue by pandaskii** [govCMS/govcms8-installer#7]
PHP 7.2.0 was released on 30 Nov 2017. govCMS8 is currently incompatible with PHP 7.2 due.

- [PHP Supported Versions](http://php.net/supported-versions.php)
- [Drupal core is still not fully compatible with PHP 7.2](https://www.drupal.org/project/issues/search/drupal?project_issue_followers=&status%5B%5D=1&status%5B%5D=13&status%5B%5D=8&status%5B%5D=14&status%5B%5D=15&status%5B%5D=4&status%5B%5D=16&version%5B%5D=8.x&version%5B%5D=7.x&issue_tags_op=%3D&issue_tags=PHP+7.2)

**Comment by govhosting** [comment]
Drupal 8.5 is PHP 7.2 compatible.

**Comment by OPCIT** [comment]
It's important that the instructions for 'Via Composer Create-Project' be updated to specify the PHP 7.1 is required for this to work.

Using either 7.0.x or 7.2 both results in errors in one form or another during setup and installation.

PHP 7.0.x - During composer build
govcms/govcms 1.x-dev requires php ^7.1 -> your PHP version (7.0.32) does not satisfy that requirement.

PHP 7.2 - During site install
Fatal error: Declaration of Drupal\field_layout\Entity\FieldLayoutEntityDisplayTrait::preSave(Drupal\Core\Entity\EntityStorageInterface $storage) must be compatible with Drupal\Core\Entity\EntityDisplayBase::preSave(Drupal\Core\Entity\EntityStorageInterface $storage, $update = true) in /home/devboxco/public_html/gov8base.dev-box.com.au/docroot/core/modules/field_layout/src/Entity/FieldLayoutEntityFormDisplay.php on line 11

**Comment by tobybellwood** [comment]
I _think_ that the new release today of GovCMS8 (alpha8) should fix the 7.2 problem (call it intuition, and if it works, I'll take credit)...

As for 7.0 - yeah, we'll update the instructions.

**Comment by OPCIT** [comment]
Thanks Toby.
Just re-ran the install and noted the updates to core and contrib modules….outstanding!
I’ve re-run the composer install using PHP 7.2 and it now completes correctly with the latest 8.6.2 version of core.

**Comment by tobybellwood** [comment]
beauty - the reason for the weird error was that the govcms8-package composer.json didn't itself contain the custom package repositories used in govcms/govcms (govcms-asset was included as a shim from alpha4 to alpha7) - so it couldn't resolve dependencies, which meant it installed alpha3, which was drupal/core:8.4.3 - notably not PHP7.2 compatible!
