### ISSUE TITLE
Playing with Docker

### ISSUE THREAD

**Issue by pulsating-brain** [govCMS/govcms8-installer#8]
Your README says let you know if you develop other install methods. I've just got a Docker stack doing rolling updates using these 3 github repositories and Docker Cloud:

Github:
Stack file and config resources: https://github.com/pulsating-brain/docker-drupal
GovCMS8 Dockerfile etc: https://github.com/pulsating-brain/govcms8
Mariadb with UTF8MB4 dockerfile: https://github.com/pulsating-brain/database

Docker Cloud:
https://cloud.docker.com/swarm/markfuller/repository/docker/markfuller/govcms8/general
https://cloud.docker.com/swarm/markfuller/repository/docker/markfuller/database/general

Known issues:
vulnerabilities in base layers - looking to move to Alpine for the OS then go from there.
geolocation with Geocoder and Geofield not working yet

**Comment by pandaskii** [comment]
Highly appreciated for the contribution

https://github.com/govCMS/govCMS8/wiki/Other-Platforms
