### ISSUE TITLE
Media Management using Core Media Module

### ISSUE THREAD

**Issue by IvanZugec** [govCMS/govcms8-installer#82]
Add the ability to upload media assets using the core Media module. 

## Functionality

- Embed assets into via the editor using Entity Embed
- Browse assets using Entity Browser
- Use DropzoneJS for bulk upload
- Convert existing Attachments and Featured image fields to Media fields

## Media type

The following media types will be created:
- Image
- File (for documents)
- Video (uploading MP4 files, but not sure how common it is to just upload mp4 files)
- Audio (used for uploading mp3 files)
- Remote video (used for embedding YouTube or Vimeo videos) If someone has a better name for it leave a comment.

## Required Modules

- https://www.drupal.org/project/entity_embed
- https://www.drupal.org/project/entity_browser
- https://www.drupal.org/project/dropzonejs

I believe all of these modules are already in GovCMS8.

**Comment by IvanZugec** [comment]
@tobybellwood I'm think we'll start with these four media types:

- Image
- File (for documents)
- Video (uploading MP4 files)
- Remote video (used for embedding YouTube or Vimeo videos)
- Audio (is this required?)

**Comment by tobybellwood** [comment]
Nice start

We do need Audio - there are some agencies who use it.
For Embeddable video, let's keep an eye on https://www.drupal.org/project/drupal/issues/2831944 (oEmbed in core media) to make sure we either use it, or don't duplicate/deviate

**Comment by IvanZugec** [comment]
Created PR #86

**Comment by tobybellwood** [comment]
Merged

**Comment by OPCIT** [comment]
There is an known issue with linking embedded images from the editor.
This patch adds a field into the image management model to accept a link.
Selecting an image the normal way then linking does not work.
This patch helps, but might not be the best solution.
https://www.drupal.org/project/entity_embed/issues/2511404#comment-12584654

**Comment by IvanZugec** [comment]
@OPCIT , I recommend you create a new issue so it can be tracked (https://github.com/govCMS/govCMS8/issues/new).

This issue is closed.

**Comment by OPCIT** [comment]
This issue references the entity_embed module so thought it might be best to wrap it into the one issue, but I'm happy to create another.
Thanks!
